analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/UserProperty.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt

[Oztechan/CCC#1689] Delete Active currencies user property

---

common/src/commonMain/sql/com/oztechan/ccc/common/database/sql/migrations/5.sqm

[Oztechan/CCC#1685] iOS Migration crash hot-fix

---

ad/build.gradle.kts
analytics/build.gradle.kts
android/build.gradle.kts
backend/build.gradle.kts
billing/build.gradle.kts
buildSrc/src/main/kotlin/Modules.kt
client/build.gradle.kts
common/build.gradle.kts
config/build.gradle.kts
provider/build.gradle.kts
res/build.gradle.kts
test/build.gradle.kts

[Oztechan/CCC#1703] Change Modules structure for more readable le gradle files

---

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WidgetViewModelTest.kt

[Oztechan/CCC#1696] Add simple test cases for WidgetViewModel

---

android/src/main/kotlin/com/oztechan/ccc/android/widget/AppWidgetReceiver.kt

[Oztechan/CCC#1701] Open app from widget via package name

---

ad/build.gradle.kts
analytics/build.gradle.kts
android/build.gradle.kts
backend/build.gradle.kts
billing/build.gradle.kts
buildSrc/src/main/kotlin/Modules.kt
client/build.gradle.kts
common/build.gradle.kts
config/build.gradle.kts
provider/build.gradle.kts
res/build.gradle.kts
settings.gradle.kts
test/build.gradle.kts

[Oztechan/CCC#1705] Create Submodules structure for Git submodules

---

common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSourceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/mapper/Watcher.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/WatcherTest.kt

[Oztechan/CCC#1733] Convention for Watcher mappers and remove not necessary extensions

---

common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/conversion/ConversionDataSourceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/mapper/Conversion.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/mapper/ExchangeRate.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/ConversionTest.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/ExchangeRateTest.kt

[Oztechan/CCC#1739] Convention for Conversion mappers and remove not necessary extensions

---

config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/AdConfig.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/ReviewConfig.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/UpdateConfig.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/ad/AdConfig.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/ad/AdConfigServiceImpl.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/review/ReviewConfig.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/review/ReviewConfigServiceImpl.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/update/UpdateConfig.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/update/UpdateConfigServiceImpl.kt
config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/AdConfigTest.kt
config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/ReviewConfigTest.kt
config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/UpdateConfigTest.kt

[Oztechan/CCC#1741] Convention for Remote Config mappers and remove not necessary extensions

---

common/build.gradle.kts
common/core/database/build.gradle.kts
common/core/database/src/commonMain/kotlin/com/oztechan/ccc/common/core/database/base/BaseDBDataSource.kt
common/core/database/src/commonMain/kotlin/com/oztechan/ccc/common/core/database/error/DatabaseException.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/base/BaseNetworkService.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/error/EmptyParameterException.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/error/ModelMappingException.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/error/NetworkException.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/error/TerminationException.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/error/TimeoutException.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/error/UnknownNetworkException.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/conversion/ConversionDataSourceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSourceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSourceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/error/DatabaseException.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/error/EmptyParameterException.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/error/ModelMappingException.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/error/NetworkException.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/error/TimeoutException.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/error/UnknownNetworkException.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/service/backend/BackendApiServiceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/service/free/FreeApiServiceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/service/premium/PremiumApiServiceImpl.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/BaseDataSourceTest.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BackendApiServiceTest.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BaseNetworkServiceTest.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/service/FreeApiServiceTest.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/service/PremiumApiServiceTest.kt

[Oztechan/CCC#1764] Move common used classes into core modules

---

gradle.properties

[Oztechan/CCC#1772] Increase Gradle worker and the heap

---

backend/build.gradle.kts
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/client/ClientControllerImpl.kt
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/KoinModule.kt
buildSrc/src/main/kotlin/Modules.kt
common/data/service/free/.gitignore
common/data/service/free/build.gradle.kts
common/data/service/free/src/commonMain/kotlin/com/oztechan/ccc/common/data/service/free/FreeApiService.kt
common/data/service/free/src/commonMain/kotlin/com/oztechan/ccc/common/data/service/free/FreeApiServiceImpl.kt
common/data/service/free/src/commonMain/kotlin/com/oztechan/ccc/common/data/service/free/di/CommonDataServiceFreeModule.kt
common/data/service/free/src/commonTest/kotlin/com/oztechan/ccc/common/data/service/free/FreeApiServiceTest.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/di/ServiceModule.kt
settings.gradle.kts

[Oztechan/CCC#1775] Create :common:data:service:free module

---

backend/build.gradle.kts
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/server/ServerController.kt
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/server/ServerControllerImpl.kt
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/ServerModule.kt
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/CurrencyRoute.kt
backend/src/jvmTest/kotlin/com/oztechan/ccc/backend/controller/ServerControllerTest.kt
buildSrc/src/main/kotlin/SecretExt.kt
common/build.gradle.kts
common/core/network/build.gradle.kts
common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/conversion/ConversionDataSource.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/conversion/ConversionDataSourceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/exchangerate/ExchangeRateDataSource.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/exchangerate/ExchangeRateDataSourceImpl.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/di/DataSourceModule.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/mapper/ExchangeRateMapper.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/ConversionDataSourceTest.kt
common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/ExchangeRateMapperTest.kt
gradle/libs.versions.toml

[#1770] Create ExchangeRateDataSource for backend specific operations

---

android/app/build.gradle.kts
android/app/src/main/kotlin/com/oztechan/ccc/android/app/di/Koin.kt
buildSrc/src/main/kotlin/Modules.kt
client/build.gradle.kts
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WidgetViewModelTest.kt
common/data/datasource/currency/.gitignore
common/data/datasource/currency/build.gradle.kts
common/data/datasource/currency/src/commonMain/kotlin/com/oztechan/ccc/common/data/datasource/currency/CurrencyDataSource.kt
common/data/datasource/currency/src/commonMain/kotlin/com/oztechan/ccc/common/data/datasource/currency/CurrencyDataSourceImpl.kt
common/data/datasource/currency/src/commonMain/kotlin/com/oztechan/ccc/common/data/datasource/currency/di/CommonDataDatasourceCurrencyModule.kt
common/data/datasource/currency/src/commonTest/kotlin/com/oztechan/ccc/common/data/datasource/currency/CurrencyDataSourceTest.kt
common/src/commonMain/kotlin/com/oztechan/ccc/common/di/DataSourceModule.kt
provider/build.gradle.kts
provider/src/iosMain/kotlin/com/oztechan/ccc/provider/di/Koin.kt
settings.gradle.kts

[Oztechan/CCC#1784] Create :common:data:datasource:currency module

---

buildSrc/src/main/kotlin/Modules.kt
client/build.gradle.kts
client/core/remoteconfig/build.gradle.kts
client/core/remoteconfig/src/androidMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/model/AdConfig.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/model/ReviewConfig.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/model/UpdateConfig.kt
client/core/remoteconfig/src/iosMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/AdConfigMapper.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/ReviewConfigMapper.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/UpdateConfigMapper.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/ad/AdConfigServiceImpl.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/review/ReviewConfigServiceImpl.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/update/UpdateConfigServiceImpl.kt
config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/AdConfigMapperTest.kt
config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/ReviewConfigMapperTest.kt
config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/UpdateConfigMapperTest.kt
settings.gradle.kts

[Oztechan/CCC#1803] Create :client:core:remoteconfig module

---

android/app/build.gradle.kts
android/app/src/main/kotlin/com/oztechan/ccc/android/app/di/Koin.kt
buildSrc/src/main/kotlin/Modules.kt
client/build.gradle.kts
client/configservice/review/build.gradle.kts
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/ReviewConfigService.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/ReviewConfigServiceImpl.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/di/ClientConfigServiceReviewModel.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/mapper/ReviewConfigMapper.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/model/ReviewConfig.kt
client/configservice/review/src/commonTest/kotlin/com/oztechan/ccc/client/configservice/review/mapper/ReviewConfigMapperTest.kt
client/core/remoteconfig/build.gradle.kts
client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/di/ConfigModule.kt
config/src/commonMain/kotlin/com/oztechan/ccc/config/service/review/ReviewConfigService.kt
provider/build.gradle.kts
provider/src/iosMain/kotlin/com/oztechan/ccc/provider/di/Koin.kt
settings.gradle.kts

[Oztechan/CCC#1806] Create :client:configservice:review module

---

.github/workflows/main.yml
build.gradle.kts
codecov.yml
gradle/libs.versions.toml

[Oztechan/CCC#1818] Remove Sonarcloud integration and Codecov comments

---

.github/workflows/main.yml
ios/fastlane/Fastfile

[Oztechan/CCC#1840] Fix invalid IPA path

---

.github/workflows/main.yml

[Oztechan/CCC#1844] Merge repetative upload/download/delete artifact steps

---

.github/workflows/main.yml

[Oztechan/CCC#1847] Cancel jobs in parallel when current job fails

---

.github/workflows/main.yml

[Oztechan/CCC#1843] Fix android versioning issue

---

android/feature/mobile/src/main/kotlin/com/oztechan/ccc/android/feature/mobile/ui/settings/SettingsFragment.kt
client/core/viewmodel/build.gradle.kts
client/core/viewmodel/src/androidMain/kotlin/com/oztechan/ccc/client/viewmodel/util/AndroidFormatUtil.kt
client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/util/FormatUtil.kt
client/core/viewmodel/src/commonTest/kotlin/com/oztechan/ccc/client/core/viewmodel/util/FormatUtilTest.kt
client/core/viewmodel/src/iosMain/kotlin/com/oztechan/ccc/client/viewmodel/util/IOSFormatUtil.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt

[Oztechan/CCC#1842] Create FormatUtil in :client:core:viewmodel and move relevant methods from client

---

.github/workflows/main.yml

[Oztechan/CCC#1853] Create new job for uploading reports

---

android/feature/mobile/build.gradle.kts
client/core/shared/src/commonMain/kotlin/com/oztechan/ccc/client/core/shared/util/DateUtil.kt
client/core/shared/src/commonTest/kotlin/com/oztechan/ccc/client/core/shared/util/DateUtilTest.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/mapper/ExchangeRate.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/mapper/ExchangeRateTest.kt

[Oztechan/CCC#1851] Reorganise DateUtil to minimise kotlinXDatetime usage

---

.github/workflows/main.yml
codecov.yml

[Oztechan/CCC#1855] Add Sonar and codecov back

---

client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/util/CoroutineUtil.kt
client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/util/FormatUtil.kt
client/core/viewmodel/src/commonTest/kotlin/com/oztechan/ccc/client/core/viewmodel/util/FormatUtilTest.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt

[Oztechan/CCC#1863] Move CoroutinesUtil and toStandardDigits into :client:core:viewmodel

---

android/app/build.gradle.kts
android/core/ad/build.gradle.kts
android/core/billing/build.gradle.kts
android/feature/mobile/build.gradle.kts
android/feature/widget/build.gradle.kts
backend/build.gradle.kts
backend/service/free/build.gradle.kts
backend/service/premium/build.gradle.kts
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/client/ClientControllerImpl.kt
buildSrc/src/main/kotlin/config/DeviceFlavour.kt
client/build.gradle.kts
client/core/remoteconfig/build.gradle.kts
client/core/viewmodel/build.gradle.kts
client/datasource/currency/build.gradle.kts
client/datasource/currency/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/currency/CurrencyDataSourceTest.kt
client/datasource/watcher/build.gradle.kts
client/datasource/watcher/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/watcher/WatcherDataSourceTest.kt
client/repository/background/build.gradle.kts
client/repository/background/src/commonTest/kotlin/com/oztechan/ccc/client/repository/background/BackgroundRepositoryTest.kt
client/service/backend/build.gradle.kts
client/service/backend/src/commonTest/kotlin/com/oztechan/ccc/client/service/backend/BackendApiServiceTest.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/helper/BaseTest.kt
common/datasource/conversion/build.gradle.kts
common/datasource/conversion/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/conversion/ConversionDataSourceTest.kt
ios/provider/build.gradle.kts

[Oztechan/CCC#1866] Get rid of unnecessary api implementations

---

.github/workflows/main.yml

[Oztechan/CCC#1868] Move Distribute iOS job to linux

---

android/feature/mobile/build.gradle.kts
android/feature/mobile/src/main/kotlin/com/oztechan/ccc/android/feature/mobile/ui/settings/SettingsFragment.kt
client/core/shared/src/androidMain/kotlin/com/oztechan/ccc/client/core/shared/util/AndroidFormatUtil.kt
client/core/shared/src/commonMain/kotlin/com/oztechan/ccc/client/core/shared/util/FormatUtil.kt
client/core/shared/src/commonTest/kotlin/com/oztechan/ccc/client/core/shared/util/FormatUtilTest.kt
client/core/shared/src/iosMain/kotlin/com/oztechan/ccc/client/core/shared/util/IOSFormatUtil.kt
client/core/viewmodel/build.gradle.kts
client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
client/viewmodel/watchers/build.gradle.kts
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
client/viewmodel/widget/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
ios/Podfile.lock

[Oztechan/CCC#1877] Move shared utils into :client:core:shared

---

android/app/build.gradle.kts
android/app/src/main/kotlin/com/oztechan/ccc/android/app/di/Koin.kt
android/feature/mobile/build.gradle.kts
android/feature/mobile/src/main/kotlin/com/oztechan/ccc/android/feature/mobile/ui/settings/SettingsFragment.kt
android/feature/mobile/src/main/res/layout/fragment_settings.xml
buildSrc/src/main/kotlin/Modules.kt
client/src/commonMain/kotlin/com/oztechan/ccc/client/di/ViewModelModule.kt
client/viewmodel/settings/build.gradle.kts
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/di/ClientViewModelSettingsModule.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/di/ClientViewModelWatchersModule.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
ios/provider/build.gradle.kts
ios/provider/src/iosMain/kotlin/com/oztechan/ccc/ios/provider/di/Koin.kt
settings.gradle.kts

[Oztechan/CCC#1882] Create :client:viewmodel:settings module

---

.github/workflows/main.yml

[Oztechan/CCC#1900] Don't let CodeAnalysis to fail other jobs

---

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/client/ClientControllerImpl.kt
backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/ClientModule.kt
client/core/shared/src/commonTest/kotlin/com/oztechan/ccc/client/core/shared/util/DateUtilTest.kt
client/repository/adcontrol/build.gradle.kts
client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
client/viewmodel/main/build.gradle.kts
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
client/viewmodel/premium/build.gradle.kts
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt
client/viewmodel/widget/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModelTest.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/constants/TimeConstants.kt

[Oztechan/CCC#1896] Get rid of time constants

---

client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt

[Oztechan/CCC#1904] Fix infinite loop in test case

---

android/app/build.gradle.kts
android/feature/mobile/build.gradle.kts
backend/build.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#1910] Remove Java 8 and desugaring

---

.github/workflows/main.yml
gradle.properties
settings.gradle.kts

[Oztechan/CCC#1906] Add Gradle build scan and update properties

---

.github/workflows/main.yml

[Oztechan/CCC#1920] Fix wrong artifact deleting issue

---

.github/workflows/main.yml

[Oztechan/CCC#1943] Fix android App distribution issue

---

android/viewmodel/premium/src/test/kotlin/com/oztechan/ccc/android/viewmodel/premium/PremiumViewModelTest.kt
client/datasource/currency/client-datasource-currency.gradle.kts
client/datasource/currency/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/currency/CurrencyDataSourceTest.kt
client/datasource/watcher/client-datasource-watcher.gradle.kts
client/datasource/watcher/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/watcher/WatcherDataSourceTest.kt
client/repository/adcontrol/client-repository-adcontrol.gradle.kts
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/service/backend/client-service-backend.gradle.kts
client/storage/app/client-storage-app.gradle.kts
client/storage/app/src/commonTest/kotlin/com/oztechan/ccc/client/storage/app/AppStorageTest.kt
client/storage/calculation/client-storage-calculation.gradle.kts
client/storage/calculation/src/commonTest/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageTest.kt
client/viewmodel/calculator/client-viewmodel-calculator.gradle.kts
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/currencies/client-viewmodel-currencies.gradle.kts
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
client/viewmodel/main/client-viewmodel-main.gradle.kts
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
client/viewmodel/selectcurrency/client-viewmodel-selectcurrency.gradle.kts
client/viewmodel/settings/client-viewmodel-settings.gradle.kts
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt
client/viewmodel/watchers/client-viewmodel-watchers.gradle.kts
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
common/datasource/conversion/common-datasource-conversion.gradle.kts
common/datasource/conversion/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/conversion/ConversionDataSourceTest.kt
ios/repository/background/ios-repository-background.gradle.kts

[Oztechan/CCC#1945] Fix ksp warnings and stubsUnitByDefault only in necessary mocks

---

client/core/res/client-core-res.gradle.kts
ios/provider/ios-provider.gradle.kts

[Oztechan/CCC#1708] Set cocoapods dependencies to be static

---

android/ui/mobile/android-ui-mobile.gradle.kts
android/ui/widget/android-ui-widget.gradle.kts
common/core/database/common-core-database.gradle.kts
gradle/libs.versions.toml
ios/CCC.xcodeproj/project.pbxproj
ios/Podfile.lock
ios/provider/ios-provider.gradle.kts
ios/provider/src/iosMain/kotlin/com/oztechan/ccc/ios/provider/di/Koin.kt
settings.gradle.kts

[Oztechan/CCC#1948] Kotlin 1.8.0 update

---

.github/workflows/main.yml

[Oztechan/CCC#1954] Put Coverage report into build to prevent including code analysis

---

backend/controller/sync/src/main/kotlin/com/oztechan/ccc/backend/controller/sync/SyncControllerImpl.kt
backend/service/premium/src/main/kotlin/com/oztechan/ccc/backend/service/premium/PremiumApiService.kt
backend/service/premium/src/main/kotlin/com/oztechan/ccc/backend/service/premium/PremiumApiServiceImpl.kt
backend/service/premium/src/test/kotlin/com/oztechan/ccc/backend/service/premium/PremiumApiServiceTest.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/api/premium/PremiumApi.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/api/premium/PremiumApiImpl.kt

[Oztechan/CCC#1959] Change return type ExchangeRate to Conversion in PremiumAPIService

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorAdapter.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
client/datasource/currency/src/commonMain/kotlin/com/oztechan/ccc/client/datasource/currency/mapper/CurrencyMapper.kt
client/datasource/currency/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/currency/mapper/CurrencyMapperTest.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/util/CalculatorUtil.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/util/CalculatorUtilTest.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/Currency.kt
ios/CCC/UI/Calculator/CalculatorItemView.swift
ios/Podfile.lock

[Oztechan/CCC#1950] Revert back to formatted strings on the screen

---

android/app/src/main/kotlin/com/oztechan/ccc/android/app/di/Koin.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/module/KoinModule.kt
client/core/analytics/src/androidMain/kotlin/com/oztechan/ccc/client/core/analytics/di/AndroidClientCoreAnalyticsModule.kt
client/core/analytics/src/iosMain/kotlin/com/oztechan/ccc/client/core/analytics/di/IOSClientCoreAnalyticsModule.kt
ios/provider/src/iosMain/kotlin/com/oztechan/ccc/ios/provider/di/Koin.kt
settings.gradle.kts

[Oztechan/CCC#1941] Update order of modules, structures and comments

---

README.md

[Oztechan/CCC#1969] Update README.md for Modularization and Architecture

---

renovate.json

[Oztechan/CCC#1973] Group Kotlin dependencies together for renovate

---

gradle.properties
ios/Podfile.lock

[Oztechan/CCC#1979] Update gradle properties

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#1411] Replace fastlane action with manual fastlane

---

client/configservice/ad/client-configservice-ad.gradle.kts
client/configservice/review/client-configservice-review.gradle.kts
client/configservice/update/client-configservice-update.gradle.kts
client/core/analytics/client-core-analytics.gradle.kts
client/core/persistence/client-core-persistence.gradle.kts
client/core/remoteconfig/client-core-remoteconfig.gradle.kts
client/core/res/client-core-res.gradle.kts
client/core/viewmodel/client-core-viewmodel.gradle.kts
client/datasource/currency/client-datasource-currency.gradle.kts
client/datasource/watcher/client-datasource-watcher.gradle.kts
client/repository/adcontrol/client-repository-adcontrol.gradle.kts
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/service/backend/client-service-backend.gradle.kts
client/storage/app/client-storage-app.gradle.kts
client/storage/calculation/client-storage-calculation.gradle.kts
client/viewmodel/calculator/client-viewmodel-calculator.gradle.kts
client/viewmodel/currencies/client-viewmodel-currencies.gradle.kts
client/viewmodel/main/client-viewmodel-main.gradle.kts
client/viewmodel/selectcurrency/client-viewmodel-selectcurrency.gradle.kts
client/viewmodel/settings/client-viewmodel-settings.gradle.kts
client/viewmodel/watchers/client-viewmodel-watchers.gradle.kts
common/core/database/common-core-database.gradle.kts
common/core/network/common-core-network.gradle.kts
common/datasource/conversion/common-datasource-conversion.gradle.kts
gradle.properties

[Oztechan/CCC#1981] Move to kotlin.mpp.androidSourceSetLayoutVersion=2

---

client/core/persistence/client-core-persistence.gradle.kts
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceImpl.kt
client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceTest.kt

[Oztechan/CCC#1956] Create test cases for Persistence

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt
client/core/res/src/commonMain/resources/MR/base/strings.xml
ios/CCC/UI/Settings/SettingsView.swift

[Oztechan/CCC#1990] Show when Premium will expire or expired

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/action/WidgetAction.kt
android/ui/widget/src/test/kotlin/com/oztechan/ccc/android/ui/widget/action/WidgetActionTest.kt

[Oztechan/CCC#1992] Map system widget update action to WidgetActions and prevent unnecessary refresh

---

android/app/android-app.gradle.kts
buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#2007] Set Java Versions to 11 for android modules

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt

[Oztechan/CCC#1994] Update all the Widget instances when refresh action triggered

---

.github/workflows/release.yml

[Oztechan/CCC#1985] Add auto release generation job to release CI

---

client/repository/adcontrol/src/commonMain/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryImpl.kt
client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt

[Oztechan/CCC#2018] move isPremium logic of show interstitial into AdControlRepository

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt
client/core/res/src/commonMain/resources/MR/base/strings.xml
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt

[Oztechan/CCC#2030] Copy&Paste from Clipboard for Android

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt

[Oztechan/CCC#2027] Remove empty Row for Watchers

---

ios/CCC/Resources/Info.plist

[Oztechan/CCC#2002] Add Complying with Encryption Export Regulations in info.plist

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
ios/Podfile.lock

[Oztechan/CCC#2040] iOS Few currency Snack appears on start

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#2045] Remove extra few currency effect

---

android/app/android-app.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2042] Add android desugaring for lower version of Android devices

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/FooterView.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/HeaderView.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetItem.kt

[Oztechan/CCC#2048] Increase sizes of widget clickable items

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
ios/CCC/UI/Calculator/OutputView.swift

[Oztechan/CCC#2047] Fix click on output no longer trigger event bug

---

.github/workflows/main.yml

[Oztechan/CCC#2055] Fix iOS version bug

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#2052] Remove Debounce and set active currencies at initiation time

---

client/core/analytics/src/commonMain/kotlin/com/oztechan/ccc/client/core/analytics/model/UserProperty.kt
client/viewmodel/watchers/client-viewmodel-watchers.gradle.kts
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/di/ClientViewModelWatchersModule.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt

[Oztechan/CCC#2038] Track number of active watcher

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetView.kt
android/ui/widget/src/main/res/xml/app_widget_info.xml
client/core/res/src/commonMain/resources/MR/base/strings.xml

[Oztechan/CCC#2050] Create Resources for widget items

---

android/viewmodel/premium/src/main/kotlin/com/oztechan/ccc/android/viewmodel/premium/PremiumViewModel.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
client/core/shared/src/commonMain/kotlin/com/oztechan/ccc/client/core/shared/util/DateUtil.kt
client/core/shared/src/commonTest/kotlin/com/oztechan/ccc/client/core/shared/util/DateUtilTest.kt
client/repository/adcontrol/src/commonMain/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryImpl.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#2020] Rename isItOver to isPassed and also create isNotPassed for readability

---

backend/controller/sync/src/main/kotlin/com/oztechan/ccc/backend/controller/sync/SyncControllerImpl.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/CurrencyType.kt

[Oztechan/CCC#2061] Update new currencies and the popular ones

---

common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/di/CommonCoreNetworkModule.kt

[Oztechan/CCC#2067] Fix contentType issue since old versions are still expecting any

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/module/SyncModule.kt
backend/controller/sync/src/main/kotlin/com/oztechan/ccc/backend/controller/sync/SyncController.kt
backend/controller/sync/src/main/kotlin/com/oztechan/ccc/backend/controller/sync/SyncControllerImpl.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/CurrencyType.kt

[Oztechan/CCC#2063] Create primary, secondary and tertiary currencies to fetch them according to usage

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#2065] Increase minor version

---

android/core/ad/android-core-ad.gradle.kts
android/core/billing/android-core-billing.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
buildSrc/src/main/kotlin/config/BuildType.kt
buildSrc/src/main/kotlin/config/DeviceFlavour.kt
buildSrc/src/main/kotlin/config/Keys.kt

[Oztechan/CCC#2072] Fix build warnings

---

android/core/ad/android-core-ad.gradle.kts
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/Ads.kt
android/core/billing/android-core-billing.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
buildSrc/src/main/kotlin/config/DeviceFlavour.kt
gradle/libs.versions.toml
settings.gradle.kts

[Oztechan/CCC#2074] Integrate Huawei Ad SDK

---

android/app/android-app.gradle.kts
buildSrc/src/main/kotlin/config/key/Fakes.kt
buildSrc/src/main/kotlin/config/key/Key.kt
buildSrc/src/main/kotlin/config/key/KeyUtil.kt
common/core/network/common-core-network.gradle.kts

[Oztechan/CCC#2088] Create Key for single usage secrets

---

android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt

[Oztechan/CCC#2075] Add Huawei Banner Ads

---

android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt

[Oztechan/CCC#2077] Add Huawei Rewarded Ads

---

android/core/ad/src/google/AndroidManifest.xml
android/core/ad/src/huawei/AndroidManifest.xml

[Oztechan/CCC#2095] Set Huawei and Google Advertisement ID in different manifests

---

.github/workflows/project.yml

[Oztechan/CCC#2101] Add manual issue automation

---

android/core/ad/src/google/AndroidManifest.xml
android/core/ad/src/huawei/AndroidManifest.xml
android/core/ad/src/main/AndroidManifest.xml

[Oztechan/CCC#2109] Add main manifest to ad module in order to receive merged manifest

---

.github/workflows/project.yml

[Oztechan/CCC#2103] Remove double automations

---

.github/workflows/main.yml

[Oztechan/CCC#2119] Use fetch-depth: 0 only when necessary and get rid of unnecessary checkouts

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#2129] Increase coverage in WidgetViewModel

---

android/app/android-app.gradle.kts
android/app/src/main/kotlin/com/oztechan/ccc/android/app/di/Koin.kt
android/ui/mobile/android-ui-mobile.gradle.kts
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumAdapter.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
android/viewmodel/premium/src/main/kotlin/com/oztechan/ccc/android/viewmodel/premium/di/AndroidViewModelPremiumModule.kt
buildSrc/src/main/kotlin/Modules.kt
client/viewmodel/premium/client-viewmodel-premium.gradle.kts
client/viewmodel/premium/src/main/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumSEED.kt
client/viewmodel/premium/src/main/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/premium/src/main/kotlin/com/oztechan/ccc/client/viewmodel/premium/di/ClientViewModelPremiumModule.kt
client/viewmodel/premium/src/test/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
settings.gradle.kts

[Oztechan/CCC#2122] Move :viewmodel:premium to Client

---

ios/Podfile.lock
ios/provider/ios-provider.gradle.kts
ios/provider/src/iosMain/kotlin/com/oztechan/ccc/ios/provider/di/Koin.kt

[Oztechan/CCC#2132] Integrate :client:viewmodel:premium and :client:core:shared into iOS

---

android/app/google-services.json

[Oztechan/CCC#2143] Secure Firebase key

---

ios/CCC/UI/Settings/SettingsView.swift
ios/CCC/Util/RewardedAd.swift
ios/CCC/Util/SecretUtil.swift

[Oztechan/CCC#2136] Change RewardedAd syntax

---

CCC.gradle.kts
client/core/res/client-core-res.gradle.kts

[Oztechan/CCC#2111] Enable back detekt in res module and setup tasks dependencies

---

client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/model/PremiumStatus.kt

[Oztechan/CCC#2167] Create PremiumStatus for client

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt

[Oztechan/CCC#2168] Move Android to PremiumStatus

---

ios/CCC/UI/Settings/SettingsView.swift

[Oztechan/CCC#2169] Move iOS to PremiumStatus

---

client/configservice/ad/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/ad/AdConfigServiceImpl.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/ReviewConfigServiceImpl.kt
client/configservice/update/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/update/UpdateConfigServiceImpl.kt

[Oztechan/CCC#2145] Parsing remote config issue

---

client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#2170] Remove old logic for premium status

---

client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#2171] Create tests for PremiumStatus

---

ios/CCC/UI/Calculator/CalculatorView.swift
ios/CCC/UI/Currencies/CurrenciesView.swift
ios/CCC/UI/Premium/PremiumView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Settings/SettingsView.swift
ios/CCC/UI/Watchers/WatchersView.swift
ios/CCC/Util/ConversionState.swift

[Oztechan/CCC#2177] Improve casting in switch cases

---

ios/CCC/Application.swift
ios/CCC/DI/Koin.swift
ios/CCC/UI/Calculator/CalculatorView.swift
ios/CCC/UI/Calculator/KeyboardView.swift
ios/CCC/UI/Currencies/CurrenciesView.swift
ios/CCC/UI/Premium/PremiumView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Settings/SettingsView.swift
ios/CCC/UI/Watchers/WatchersView.swift
ios/CCC/Util/ConversionState.swift
ios/CCC/Util/ObservableSEEDViewModel.swift
ios/CCC/Util/RewardedAd.swift
ios/CCC/Util/ViewExt.swift

[Oztechan/CCC#2179] Improve SwiftLint suppresses and remove not necessary ones

---

.github/workflows/release.yml
ios/fastlane/Fastfile

[Oztechan/CCC#2181] Rename fastlane build for store

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#2183] Update name CI of jobs

---

ios/CCC/UI/Currencies/CurrenciesToolbarView.swift

[Oztechan/CCC#2188] iOS search bar is so small

---

ios/CCC/UI/Currencies/CurrenciesToolbarView.swift

[Oztechan/CCC#2189] iOS SearchBar change resize the toolbar

---

ios/CCC/UI/Currencies/SelectionView.swift

[Oztechan/CCC#2192] iOS Fix Selection background

---

client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt

[Oztechan/CCC#2196] iOS first currency selection shakes list

---

client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt

[Oztechan/CCC#2198] Remove SelectionVisibility reset when currency list is updated

---

ios/CCC/UI/Calculator/InputView.swift
ios/CCC/UI/Currencies/CurrenciesToolbarView.swift
ios/CCC/UI/Currencies/SelectionView.swift

[Oztechan/CCC#2194] iOS design alignment

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/slider/SliderFragment.kt

[Oztechan/CCC#2200] Make Fragment methods binding extensions

---

.github/workflows/main.yml
.github/workflows/publish.yml
.github/workflows/release.yml

[Oztechan/CCC#2185] Create workflow for publishing release

---

PrivacyPolicy.md

[Oztechan/CCC#2203] Update Privacy Policy

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt

[Oztechan/CCC#2206] Refactor CalculateOutput method

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#2208] Separate TooBigNumber to TooBigInput and TooBigOutput

---

ios/CCC/UI/Calculator/CalculatorView.swift

[Oztechan/CCC#2211] Move iOS to new Input/Output check

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/watchers/WatchersView.kt
client/core/res/src/commonMain/resources/MR/base/strings.xml
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
ios/CCC/UI/Calculator/CalculatorView.swift
ios/CCC/UI/Watchers/WatchersView.swift

[Oztechan/CCC#2214] Remove/Replace TooBigNumber logic

---

ios/CCC/Util/InterstitialAd.swift

[Oztechan/CCC#2220] Fix iOS Interstitial ad crash when attempting to show it on background

---

.github/workflows/main.yml

[Oztechan/CCC#2225] Fix missing commit message for Firebase App Distribution builds

---

android/app/src/main/kotlin/com/oztechan/ccc/android/app/Application.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/Dialog.kt
backend/controller/sync/src/main/kotlin/com/oztechan/ccc/backend/controller/sync/SyncControllerImpl.kt
buildSrc/src/main/kotlin/config/DeviceFlavour.kt
client/core/analytics/src/commonMain/kotlin/com/oztechan/ccc/client/core/analytics/model/ScreenName.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/CurrencyType.kt
ios/provider/src/iosMain/kotlin/com/oztechan/ccc/ios/provider/di/Koin.kt

[Oztechan/CCC#2227] Remove unnecessary `unused` suppressions

---

android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#2243] Fix SearchView crash

---

android/ui/widget/android-ui-widget.gradle.kts
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt
client/core/analytics/src/commonMain/kotlin/com/oztechan/ccc/client/core/analytics/model/UserProperty.kt

[Oztechan/CCC#2253] Track weather a user has widget or not

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumAdapter.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/PurchaseUtil.kt
android/ui/mobile/src/test/kotlin/com/oztechan/ccc/android/ui/mobile/util/PurchaseUtilTest.kt
client/viewmodel/premium/client-viewmodel-premium.gradle.kts
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumSEED.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/model/OldPurchase.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/model/PremiumData.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/model/PremiumType.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/util/PremiumUtil.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/model/PremiumTypeTest.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/util/PremiumUtilTest.kt

[Oztechan/CCC#2259] Move premium related models and utils into :client:viewmodel:premium module

---

settings.gradle.kts

[Oztechan/CCC#2278] Remove Gradle Build Scan

---

.github/workflows/main.yml
.github/workflows/release.yml
buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#2297] Move to Java 17

---

client/core/res/client-core-res.gradle.kts

[Oztechan/CCC#2282] Remove moko resources workarounds

---

gradle.properties

[Oztechan/CCC#2308] Remove disableAutomaticComponentCreation

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt

[Oztechan/CCC#2311] Make BaseActivity abstract and move the layout into extenders

---

android/app/android-app.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
client/core/remoteconfig/src/androidMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt

[Oztechan/CCC#2313] Create build config only in necessary modules

---

gradle.properties

[Oztechan/CCC#2315] Set nonTransitiveRClass to false temporary

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt

[Oztechan/CCC#2317] Fix wrong fragment container id

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/watchers/WatchersView.kt

[Oztechan/CCC#1971] Pass event instead of lambdas in Compose

---

renovate.json

[Oztechan/CCC#2335] Update Renovate package patterns to exclude coroutines from Kotlin updates

---

gradle/wrapper/gradle-wrapper.properties

[Oztechan/CCC#2348] Build Error Fix

---

ios/repository/background/src/commonMain/kotlin/com/oztechan/ccc/ios/repository/background/BackgroundRepositoryImpl.kt

[Oztechan/CCC#2322] Avoid Throwable.kt line 27 non-fatal as crash in iOS

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#2353] Move to Gradle build action v2.4.2

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidget.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/action/WidgetAction.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/HeaderView.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetView.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#2387] Create onPreviousClick Event

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/action/WidgetAction.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetView.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt

[Oztechan/CCC#2388] Create onNextClick Event

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/action/WidgetAction.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/FooterView.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetView.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt

[Oztechan/CCC#2395] Create onRefreshClick Event

---

android/ui/widget/android-ui-widget.gradle.kts
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidget.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/action/WidgetAction.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/FooterView.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetView.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt

[Oztechan/CCC#2397] Create onAppOpenClick Event and Effect

---

client/core/remoteconfig/src/androidMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt

[Oztechan/CCC#2319] Don't Log first time cache check errors for RemoteConfig

---

gradle.properties

[Oztechan/CCC#2419] Move gradle to allWarningsAsErrors

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt

[Oztechan/CCC#2428] Simplify AppWidgetReceiver class

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#2430] Remove refreshWidgetData and update failed test cases

---

android/app/android-app.gradle.kts
android/core/billing/android-core-billing.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
backend/app/backend-app.gradle.kts
buildSrc/src/main/kotlin/Modules.kt
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/viewmodel/calculator/client-viewmodel-calculator.gradle.kts
client/viewmodel/currencies/client-viewmodel-currencies.gradle.kts
client/viewmodel/premium/client-viewmodel-premium.gradle.kts
ios/provider/ios-provider.gradle.kts
settings.gradle.kts

[Oztechan/CCC#1927] Move submodules to compositeBuilds

---

android/app/android-app.gradle.kts
android/core/billing/android-core-billing.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
backend/app/backend-app.gradle.kts
buildSrc/src/main/kotlin/Modules.kt
buildSrc/src/main/kotlin/Submodules.kt
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/viewmodel/calculator/client-viewmodel-calculator.gradle.kts
client/viewmodel/currencies/client-viewmodel-currencies.gradle.kts
client/viewmodel/premium/client-viewmodel-premium.gradle.kts
ios/provider/ios-provider.gradle.kts

[Oztechan/CCC#2432] Extract the submodules to its own object

---

.github/workflows/release.yml

[Oztechan/CCC#2434] Delete HUAWEI_APP_ID from CI and add into codebase statically

---

ios/CCC.xcodeproj/project.pbxproj

[Oztechan/CCC#2444] Fix iOS build

---

ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/Podfile.lock

[Oztechan/CCC#2445] Update iOS libraries

---

renovate.json

[Oztechan/CCC#2452] Group git submodule updates

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC.xcodeproj/xcshareddata/xcschemes/CCC.xcscheme

[Oztechan/CCC#2449] Xcode 14.3.1 improvements

---

backend/service/free/src/test/kotlin/com/oztechan/ccc/backend/service/free/FreeApiServiceTest.kt
backend/service/premium/src/test/kotlin/com/oztechan/ccc/backend/service/premium/PremiumApiServiceTest.kt
client/service/backend/src/commonTest/kotlin/com/oztechan/ccc/client/service/backend/BackendApiServiceTest.kt

[Oztechan/CCC#2456] Fix expected invocations for Service classes

---

client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt

[Oztechan/CCC#2464] Fix expected invocations for AdControlRepositoryTest

---

client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#2467] Fix expected invocations for CalculatorViewModelTest

---

client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt

[Oztechan/CCC#2468] Fix expected invocations for PremiumViewModelTest

---

client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#2469] Fix expected invocations for SettingsViewModelTest

---

client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt

[Oztechan/CCC#2473] Few Currency effect bug fix when list is filtered

---

client/core/remoteconfig/src/androidMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt

[Oztechan/CCC#2476] Avoid empty RemoteConfig value parsing

---

client/core/res/client-core-res.gradle.kts

[Oztechan/CCC#2483] Specify moko resources paths

---

common/core/network/common-core-network.gradle.kts

[Oztechan/CCC#2481] Add coroutines into common.core.network

---

android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/AppWidgetReceiver.kt
android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetView.kt
client/core/analytics/src/androidMain/kotlin/com/oztechan/ccc/client/core/analytics/AnalyticsManagerImpl.kt

[Oztechan/CCC#2482] Add iterator() for the java API usages

---

CCC.gradle.kts
gradle.properties

[Oztechan/CCC#2478] Temporary disable allWarningsAsErrors

---

android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#2490] Add onNextClick event test case

---

android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#2492] Add onPreviousClick event test case

---

android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#2494] Add missing event test cases

---

android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#2496] Add test for ArrayIndexOutOfBoundsException

---

gradle.properties

[Oztechan/CCC#2501] Remove V2 androidSourceSetLayoutVersion

---

client/configservice/ad/client-configservice-ad.gradle.kts
client/configservice/review/client-configservice-review.gradle.kts
client/configservice/update/client-configservice-update.gradle.kts
client/core/analytics/client-core-analytics.gradle.kts
client/core/persistence/client-core-persistence.gradle.kts
client/core/remoteconfig/client-core-remoteconfig.gradle.kts
client/core/res/client-core-res.gradle.kts
client/core/viewmodel/client-core-viewmodel.gradle.kts
client/datasource/currency/client-datasource-currency.gradle.kts
client/datasource/watcher/client-datasource-watcher.gradle.kts
client/repository/adcontrol/client-repository-adcontrol.gradle.kts
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/service/backend/client-service-backend.gradle.kts
client/storage/app/client-storage-app.gradle.kts
client/storage/calculation/client-storage-calculation.gradle.kts
client/viewmodel/calculator/client-viewmodel-calculator.gradle.kts
client/viewmodel/currencies/client-viewmodel-currencies.gradle.kts
client/viewmodel/main/client-viewmodel-main.gradle.kts
client/viewmodel/premium/client-viewmodel-premium.gradle.kts
client/viewmodel/selectcurrency/client-viewmodel-selectcurrency.gradle.kts
client/viewmodel/settings/client-viewmodel-settings.gradle.kts
client/viewmodel/watchers/client-viewmodel-watchers.gradle.kts
common/core/database/common-core-database.gradle.kts
common/core/network/common-core-network.gradle.kts
common/datasource/conversion/common-datasource-conversion.gradle.kts

[Oztechan/CCC#2505] move kotlin android definition to androidTarget

---

gradle.properties

[Oztechan/CCC#2509] Enable back allWarningsAsErrors gradle property

---

common/core/database/src/commonTest/kotlin/com/oztechan/ccc/common/core/database/base/BaseDBDataSourceTest.kt
common/core/network/src/commonTest/kotlin/com/oztechan/ccc/common/core/network/base/BaseNetworkServiceTest.kt

[Oztechan/CCC#2511] Remove exception message checking test cases

---

client/configservice/ad/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/ad/AdConfigServiceImpl.kt
client/configservice/ad/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/ad/mapper/AdConfigMapper.kt
client/configservice/ad/src/commonTest/kotlin/com/oztechan/ccc/client/configservice/ad/mapper/AdConfigMapperTest.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/ReviewConfigServiceImpl.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/mapper/ReviewConfigMapper.kt
client/configservice/review/src/commonTest/kotlin/com/oztechan/ccc/client/configservice/review/mapper/ReviewConfigMapperTest.kt
client/configservice/update/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/update/UpdateConfigServiceImpl.kt
client/configservice/update/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/update/mapper/UpdateConfigMapper.kt
client/configservice/update/src/commonTest/kotlin/com/oztechan/ccc/client/configservice/update/mapper/UpdateConfigMapperTest.kt
client/core/remoteconfig/client-core-remoteconfig.gradle.kts
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/model/AdConfig.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/model/ReviewConfig.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/model/UpdateConfig.kt

[Oztechan/CCC#2527] Move serialised models to :client:core:remoteconfig

---

client/configservice/ad/client-configservice-ad.gradle.kts
client/configservice/ad/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/ad/AdConfigServiceImpl.kt
client/configservice/review/client-configservice-review.gradle.kts
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/ReviewConfigServiceImpl.kt
client/configservice/update/client-configservice-update.gradle.kts
client/configservice/update/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/update/UpdateConfigServiceImpl.kt
client/core/remoteconfig/src/androidMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/util/Parser.kt
client/core/remoteconfig/src/iosMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt

[Oztechan/CCC#2529] Move parsing logic into :client:core:remoteconfig

---

client/core/remoteconfig/client-core-remoteconfig.gradle.kts
client/core/remoteconfig/src/commonTest/kotlin/com/oztechan/ccc/client/core/remoteconfig/util/ParserTest.kt

[Oztechan/CCC#2533] Add test cases for Parser

---

client/configservice/ad/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/ad/AdConfigServiceImpl.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/ReviewConfigServiceImpl.kt
client/configservice/update/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/update/UpdateConfigServiceImpl.kt
client/core/remoteconfig/src/androidMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
client/core/remoteconfig/src/iosMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt

[Oztechan/CCC#2531] Tidy up BaseConfig classes and use extension methods for readability

---

gradle.properties

[Oztechan/CCC#2535] Remove android.databinding.incremental

---

android/app/android-app.gradle.kts
android/core/ad/android-core-ad.gradle.kts
android/core/billing/android-core-billing.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
android/ui/widget/android-ui-widget.gradle.kts
client/core/res/client-core-res.gradle.kts

[Oztechan/CCC#2539] Remove not needed UnstableApiUsage suppresses

---

.github/workflows/main.yml
.github/workflows/publish.yml
.github/workflows/release.yml

[Oztechan/CCC#2544] Use exact versions in third party GitHub Actions

---

CCC.gradle.kts

[Oztechan/CCC#2519] Run detekt tasks only when detekt is invoked

---

ios/CCC/Util/ObservableSEEDViewModel.swift

[Oztechan/CCC#2551] Move all viewmodel logs to debug

---

android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
ios/CCC/Util/InterstitialAd.swift
ios/CCC/Util/RewardedAd.swift
ios/repository/background/src/commonMain/kotlin/com/oztechan/ccc/ios/repository/background/BackgroundRepositoryImpl.kt

[Oztechan/CCC#2566] Update all warning logs with assert and error if necessary

---

client/core/viewmodel/src/androidMain/kotlin/com/oztechan/ccc/client/core/viewmodel/BaseViewModel.kt
client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/core/viewmodel/BaseViewModel.kt
client/core/viewmodel/src/iosMain/kotlin/com/oztechan/ccc/client/core/viewmodel/BaseViewModel.kt

[Oztechan/CCC#2575] Remove onCleared method from ViewModel

---

client/core/res/client-core-res.gradle.kts

[Oztechan/CCC#2581] Remove additional srcDirs for native platforms

---

client/configservice/ad/client-configservice-ad.gradle.kts
client/configservice/review/client-configservice-review.gradle.kts
client/configservice/update/client-configservice-update.gradle.kts
client/core/analytics/client-core-analytics.gradle.kts
client/core/persistence/client-core-persistence.gradle.kts
client/core/remoteconfig/client-core-remoteconfig.gradle.kts
client/core/res/client-core-res.gradle.kts
client/core/shared/client-core-shared.gradle.kts
client/core/viewmodel/client-core-viewmodel.gradle.kts
client/datasource/currency/client-datasource-currency.gradle.kts
client/datasource/watcher/client-datasource-watcher.gradle.kts
client/repository/adcontrol/client-repository-adcontrol.gradle.kts
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/service/backend/client-service-backend.gradle.kts
client/storage/app/client-storage-app.gradle.kts
client/storage/calculation/client-storage-calculation.gradle.kts
client/viewmodel/calculator/client-viewmodel-calculator.gradle.kts
client/viewmodel/currencies/client-viewmodel-currencies.gradle.kts
client/viewmodel/main/client-viewmodel-main.gradle.kts
client/viewmodel/premium/client-viewmodel-premium.gradle.kts
client/viewmodel/selectcurrency/client-viewmodel-selectcurrency.gradle.kts
client/viewmodel/settings/client-viewmodel-settings.gradle.kts
client/viewmodel/watchers/client-viewmodel-watchers.gradle.kts
common/core/database/common-core-database.gradle.kts
common/core/infrastructure/common-core-infrastructure.gradle.kts
common/core/model/common-core-model.gradle.kts
common/core/network/common-core-network.gradle.kts
common/datasource/conversion/common-datasource-conversion.gradle.kts
ios/provider/ios-provider.gradle.kts
ios/repository/background/ios-repository-background.gradle.kts

[Oztechan/CCC#2590] Move to default targetHierarchy

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/watchers/WatchersView.kt
ios/CCC.xcodeproj/project.pbxproj
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/Calculator/CalculatorView.swift
ios/CCC/UI/Currencies/CurrenciesView.swift
ios/CCC/UI/Main/MainView.swift
ios/Podfile.lock

[Oztechan/CCC#2597] Move iOS CalculatorView to CalculatorRootView

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/Currencies/CurrenciesRootView.swift
ios/CCC/UI/Currencies/CurrenciesView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Settings/SettingsView.swift
ios/CCC/UI/Slider/SliderView.swift

[Oztechan/CCC#2600] Move CurrenciesView to CurrenciesRootView

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/Application.swift
ios/CCC/UI/Main/MainRootView.swift
ios/CCC/UI/Main/MainView.swift

[Oztechan/CCC#2611] Move MainView to MainRootView

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyRootView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Watchers/WatchersView.swift
ios/Podfile.lock

[Oztechan/CCC#2613] Move SelectCurrencyView to SelectCurrencyRootView

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Settings/SettingsRootView.swift
ios/CCC/UI/Watchers/WatchersRootView.swift
ios/CCC/UI/Watchers/WatchersView.swift
ios/Podfile.lock

[Oztechan/CCC#2604] Move iOS WatchersView to WatchersRootView

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/UI/Slider/BugReportSlideRootView.swift

[Oztechan/CCC#2622] Create BugReportSlideRootView

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/UI/Slider/BugReportSlideRootView.swift
ios/CCC/UI/Slider/IntroSlideRootView.swift

[Oztechan/CCC#2623] Create IntroSlideRootView

---

ios/CCC/Application.swift
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/Currencies/CurrenciesRootView.swift
ios/CCC/UI/Settings/SettingsRootView.swift
ios/CCC/UI/Watchers/WatchersRootView.swift
ios/CCC/Util/ViewExt.swift

[Oztechan/CCC#2631] Create snack extension for PopupViews Snacks

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt
ios/CCC/UI/Settings/SettingsRootView.swift
ios/CCC/UI/Settings/SettingsView.swift

[Oztechan/CCC#2644] Move shouldShowBannerAd into State for Settings Screen

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainSEED.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
ios/CCC/UI/Main/MainRootView.swift
ios/CCC/UI/Main/MainView.swift
ios/Podfile.lock

[Oztechan/CCC#2637] Move MainViewModel isFirstRun into State

---

android/core/billing/src/google/kotlin/com/oztechan/ccc/android/core/billing/BillingManagerImpl.kt
android/core/billing/src/main/kotlin/com/oztechan/ccc/android/core/billing/BillingEffect.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt

[Oztechan/CCC#2659] Create an effect for the case that billing is not available

---

android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/main/kotlin/com/oztechan/ccc/android/core/ad/AdManager.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumSEED.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
ios/CCC/UI/Premium/PremiumRootView.swift
ios/Podfile.lock

[Oztechan/CCC#2663] Create onPremiumActivationFailed event and move loading logic into PremiumViewModel

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumSEED.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
ios/CCC/UI/Premium/PremiumRootView.swift

[Oztechan/CCC#2665] Create onPremiumActivated event

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesSEED.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
ios/CCC/UI/Currencies/CurrenciesRootView.swift
ios/CCC/UI/Currencies/CurrenciesToolbarView.swift
ios/CCC/UI/Currencies/CurrenciesView.swift

[Oztechan/CCC#2650] Move CurrenciesViewModel isFirstRun into State

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumSEED.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt

[Oztechan/CCC#2667] Create onRestorePurchase event

---

.github/workflows/release.yml

[Oztechan/CCC#2586] Change huawei app id

---

.github/workflows/project.yml
renovate.json

[Oztechan/CCC#2681] Update Renovate bot author

---

.github/workflows/project.yml

[Oztechan/CCC#2686] Update Renovate bot login

---

android/core/billing/src/google/kotlin/com/oztechan/ccc/android/core/billing/BillingManagerImpl.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
ios/CCC/UI/Premium/PremiumRootView.swift
ios/Podfile.lock

[Oztechan/CCC#2671] Fix the infinite loading issues

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/Calculator/CalculatorView.swift

[Oztechan/CCC#2642] Move shouldShowBannerAd into State for Calculator Screen

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt

[Oztechan/CCC#2652] Remove hideSelectionVisibility and custom logic in Currencies Screen

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainSEED.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt

[Oztechan/CCC#2639] Move MainViewModel getAppTheme into State

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/watchers/WatchersView.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
ios/CCC/UI/Watchers/WatchersRootView.swift
ios/CCC/UI/Watchers/WatchersView.swift

[Oztechan/CCC#2645] Move shouldShowBannerAd into State for Watchers Screen

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#2654] Refactor the theming in SettingsViewModel without public methods

---

ios/CCC/Util/ObservableSEEDViewModel.swift

[Oztechan/CCC#2703] Update State initialisation in ObservableSEEDViewModel

---

client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
ios/Podfile.lock

[Oztechan/CCC#2711] Update onboarding visibility after user clicks Done

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumSEED.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
ios/CCC/UI/Calculator/CalculatorRootView.swift

[Oztechan/CCC#2713] Add logs for missing new events

---

ios/CCC/UI/Main/MainRootView.swift
ios/CCC/UI/Main/MainView.swift

[Oztechan/CCC#2709] Move NavigationStackView into MainView

---

client/core/res/src/commonMain/resources/MR/base/strings.xml
ios/Podfile.lock

[Oztechan/CCC#2716] Update the text user has already premium

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#2718] Compile SDK 34 increase

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#2732] Move actions/checkout to exact version

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#2734] Move actions/upload-artifact to exact version

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#2738] Move actions/download-artifact to exact version

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#2740] Move actions/setup-java to exact version

---

ios/CCC/UI/Components/CurrencyImageView.swift
ios/CCC/UI/Components/SnackView.swift
ios/CCC/UI/Slides/IntroSlideRootView.swift
ios/CCC/Util/ResourceExt.swift
ios/CCC/Util/ViewExt.swift
ios/Podfile.lock

[Oztechan/CCC#2743] Add Image extensions for Moko Resources

---

ios/CCC/Application.swift
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/Calculator/KeyboardView.swift
ios/CCC/UI/Components/AlertView.swift
ios/CCC/UI/Components/MailView.swift
ios/CCC/UI/Currencies/CurrenciesRootView.swift
ios/CCC/UI/Currencies/CurrenciesToolbarView.swift
ios/CCC/UI/Currencies/CurrenciesView.swift
ios/CCC/UI/Currencies/SelectionView.swift
ios/CCC/UI/Main/MainRootView.swift
ios/CCC/UI/Premium/PremiumItemView.swift
ios/CCC/UI/Premium/PremiumRootView.swift
ios/CCC/UI/Premium/PremiumView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Settings/SettingsRootView.swift
ios/CCC/UI/Settings/SettingsToolbarView.swift
ios/CCC/UI/Settings/SettingsView.swift
ios/CCC/UI/Slides/BugReportSlideRootView.swift
ios/CCC/UI/Slides/IntroSlideRootView.swift
ios/CCC/UI/Slides/PremiumSlideRootView.swift
ios/CCC/UI/Watchers/WatcherItem.swift
ios/CCC/UI/Watchers/WatchersRootView.swift
ios/CCC/UI/Watchers/WatchersToolbarView.swift
ios/CCC/UI/Watchers/WatchersView.swift
ios/CCC/Util/ConversionState.swift
ios/CCC/Util/ResourceExt.swift
ios/CCC/Util/ViewExt.swift

[Oztechan/CCC#2747] Add String extensions for Moko Resources

---

ios/CCC/UI/Settings/SettingsView.swift
ios/CCC/Util/ConversionState.swift
ios/CCC/Util/ResourceExt.swift
ios/CCC/Util/ViewExt.swift

[Oztechan/CCC#2749] Add String extensions with extra parameter for Moko Resources

---

ios/CCC/UI/Calculator/CalculatorItemView.swift
ios/CCC/UI/Calculator/CalculatorView.swift
ios/CCC/UI/Calculator/InputView.swift
ios/CCC/UI/Calculator/KeyboardView.swift
ios/CCC/UI/Calculator/OutputView.swift
ios/CCC/UI/Components/ActionButton.swift
ios/CCC/UI/Components/AlertView.swift
ios/CCC/UI/Components/FormProgressView.swift
ios/CCC/UI/Components/SelectCurrenciesBottomView.swift
ios/CCC/UI/Components/SnackView.swift
ios/CCC/UI/Components/ToolbarButton.swift
ios/CCC/UI/Currencies/CurrenciesItemView.swift
ios/CCC/UI/Currencies/CurrenciesToolbarView.swift
ios/CCC/UI/Currencies/CurrenciesView.swift
ios/CCC/UI/Currencies/SelectionView.swift
ios/CCC/UI/Premium/PremiumItemView.swift
ios/CCC/UI/Premium/PremiumView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyItemView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Settings/SettingsItemView.swift
ios/CCC/UI/Settings/SettingsView.swift
ios/CCC/UI/Slides/SlideView.swift
ios/CCC/UI/Watchers/WatcherItem.swift
ios/CCC/UI/Watchers/WatchersToolbarView.swift
ios/CCC/UI/Watchers/WatchersView.swift
ios/CCC/Util/ConversionState.swift
ios/CCC/Util/ViewExt.swift

[Oztechan/CCC#2751] Add Color extension for Moko Resources

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/Util/KermitExt.swift
ios/Podfile.lock

[Oztechan/CCC#2781] Create Kermit extensions for iOS

---

ios/CCC/Util/KermitExt.swift
ios/Podfile.lock

[Oztechan/CCC#2783] Fix Kermit extension error in iOS

---

.github/workflows/main.yml
.github/workflows/release.yml
ios/CCC.xcodeproj/project.pbxproj
ios/Podfile.lock
ios/podfile
ios/provider/ios-provider.gradle.kts

[Oztechan/CCC#2788] Move Provider module from Pods to Gradle

---

.github/workflows/main.yml
.github/workflows/release.yml
client/core/res/client-core-res.gradle.kts
ios/CCC.xcodeproj/project.pbxproj
ios/Podfile.lock
ios/podfile

[Oztechan/CCC#2789] Move Res module from Pods to Gradle

---

.github/workflows/publish.yml

[Oztechan/CCC#2801] Auto publish the release

---

gradle.properties

[Oztechan/CCC#2796] Get rid of kotlin.native.cacheKind=none

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/core/viewmodel/BaseSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesSEED.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainSEED.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumSEED.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencySEED.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt
ios/CCC.xcodeproj/project.pbxproj
ios/CCC/Util/ObservableSEEDViewModel.swift

[Oztechan/CCC#2794] Move all BaseSEED elements to interfaces

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/module/SyncModule.kt
backend/controller/sync/src/main/kotlin/com/oztechan/ccc/backend/controller/sync/SyncControllerImpl.kt

[Oztechan/CCC#2819] Align develop with API hotfix

---

.github/workflows/release.yml

[Oztechan/CCC#2817] Set huawei app id via CI

---

common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/CurrencyType.kt

[Oztechan/CCC#2837] Rearrange popular currencies

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/module/SyncModule.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/CurrencyType.kt

[Oztechan/CCC#2839] Update currency update frequencies

---

.github/workflows/main.yml
CCC.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2154] Update kover to 0.7.4

---

.github/workflows/main.yml
CCC.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2850] Revert recent Kover update since it removes android targets

---

client/core/persistence/client-core-persistence.gradle.kts
client/core/persistence/src/androidMain/kotlin/com/oztechan/ccc/client/core/persistence/di/ClientCorePersistenceModule.android.kt
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/FlowPersistence.kt
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/FlowPersistenceImpl.kt
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/Persistence.kt
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceImpl.kt
client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceTest.kt
client/core/persistence/src/iosMain/kotlin/com/oztechan/ccc/client/core/persistence/di/ClientCorePersistenceModule.ios.kt
gradle/libs.versions.toml

[Oztechan/CCC#2855] Add Flow support for multiplatform settings

---

client/core/persistence/src/androidMain/kotlin/com/oztechan/ccc/client/core/persistence/di/ClientCorePersistenceModule.android.kt
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/FlowPersistenceImpl.kt
client/core/persistence/src/iosMain/kotlin/com/oztechan/ccc/client/core/persistence/di/ClientCorePersistenceModule.ios.kt

[Oztechan/CCC#2863] Use relevant settings for persistencs

---

CCC.gradle.kts
client/core/persistence/client-core-persistence.gradle.kts

[Oztechan/CCC#2869] Opt-in for ExperimentalSettingsApi

---

client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/SuspendPersistenceTest.kt

[Oztechan/CCC#2865] Create test for SuspendPersistence

---

client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/FlowPersistenceTest.kt

[Oztechan/CCC#2867] Create test for FlowPersistence

---

client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/FlowPersistenceTest.kt
client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceTest.kt
client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/SuspendPersistenceTest.kt

[Oztechan/CCC#2871] Add error test case for FlowPersistence

---

README.md
settings.gradle.kts
test/test.gradle.kts

[Oztechan/CCC#2885] Create test module

---

gradle/libs.versions.toml
test/src/test/kotlin/com/oztechan/ccc/test/PackagingTest.kt
test/test.gradle.kts

[Oztechan/CCC#2888] Create test cases for packaging check

---

android/ui/mobile/src/test/kotlin/com/oztechan/ccc/android/ui/mobile/util/DeviceUtilTest.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
client/configservice/ad/src/commonTest/kotlin/com/oztechan/ccc/client/configservice/ad/mapper/AdConfigMapperTest.kt
client/configservice/review/src/commonTest/kotlin/com/oztechan/ccc/client/configservice/review/mapper/ReviewConfigMapperTest.kt
client/configservice/update/src/commonTest/kotlin/com/oztechan/ccc/client/configservice/update/mapper/UpdateConfigMapperTest.kt
client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/FlowPersistenceTest.kt
client/core/remoteconfig/src/commonTest/kotlin/com/oztechan/ccc/client/core/remoteconfig/util/ParserTest.kt
client/core/shared/src/commonTest/kotlin/com/oztechan/ccc/client/core/shared/util/FormatUtilTest.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/util/PremiumUtilTest.kt
common/core/database/src/commonTest/kotlin/com/oztechan/ccc/common/core/database/base/BaseDBDataSourceTest.kt
common/core/network/src/commonTest/kotlin/com/oztechan/ccc/common/core/network/base/BaseNetworkServiceTest.kt
test/src/test/kotlin/com/oztechan/ccc/test/PackagingTest.kt
test/src/test/kotlin/com/oztechan/ccc/test/TestingPracticesTest.kt

[Oztechan/CCC#2886] Create rules for testing practices

---

test/src/test/kotlin/com/oztechan/ccc/test/ConventionTest.kt

[Oztechan/CCC#2891] Add Conventional Tests

---

.github/workflows/main.yml
.github/workflows/publish.yml
.github/workflows/release.yml

[Oztechan/CCC#2895] Replace deprecated set-output in GitHub Action files

---

CCC.gradle.kts
android/app/android-app.gradle.kts
android/core/ad/android-core-ad.gradle.kts
android/core/billing/android-core-billing.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
android/ui/widget/android-ui-widget.gradle.kts
android/viewmodel/widget/android-viewmodel-widget.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2908] Move org.jetbrains.kotlin.android to alias

---

CCC.gradle.kts
client/core/remoteconfig/client-core-remoteconfig.gradle.kts
common/core/network/common-core-network.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2899] Get rid of kotlinSerialization classpath

---

CCC.gradle.kts
android/app/android-app.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2906] Move com.android.application to alias

---

CCC.gradle.kts
android/app/android-app.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2914] Get rid of gsm classpath

---

CCC.gradle.kts
common/core/database/common-core-database.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2922] Get rid of sqlDelight classpath

---

common/core/network/common-core-network.gradle.kts
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/di/CommonCoreNetworkModule.kt
common/core/network/src/commonTest/kotlin/com/oztechan/ccc/common/core/network/api/BackendApiTest.kt
common/core/network/src/commonTest/kotlin/com/oztechan/ccc/common/core/network/api/PremiumApiTest.kt
common/core/network/src/commonTest/kotlin/com/oztechan/ccc/common/core/network/fakes/Fakes.kt
gradle/libs.versions.toml

[Oztechan/CCC#2927] Add API testing cases

---

CCC.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2916] Get rid of kover classpath

---

CCC.gradle.kts
client/core/res/client-core-res.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2918] Get rid of mokoResources classpath

---

CCC.gradle.kts
common/core/network/common-core-network.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2912] Get rid of buildKonfig classpath

---

CCC.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2920] Get rid of safeArgs classpath

---

CCC.gradle.kts
android/app/android-app.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2925] Get rid of crashlytics classpath

---

CCC.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2931] Get rid of androidGradlePlugin classpath

---

CCC.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#2933] Get rid of kotlinGradlePlugin classpath

---

settings.gradle.kts

[Oztechan/CCC#2943] Add gradle build scan to CI

---

gradle.properties

[Oztechan/CCC#2952] Update jvm args

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#2950] Remove unused ProjectSettings properties

---

settings.gradle.kts

[Oztechan/CCC#2954] Update grade file naming logic

---

.github/workflows/main.yml

[Oztechan/CCC#2981] Fail rest of the builds when CodeAnalysis fail

---

.github/workflows/project.yml

[Oztechan/CCC#2987] Move Project Automations to Global

---

client/core/analytics/src/androidMain/kotlin/com/oztechan/ccc/client/core/analytics/AnalyticsManagerImpl.kt
client/core/remoteconfig/src/androidMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/BaseConfigService.kt
gradle/libs.versions.toml

[Oztechan/CCC#3004] Get rid of ktx version of Firebase SDKs

---

gradle.properties

[Oztechan/CCC#3023] Xcode build Fix

---

gradle/libs.versions.toml

[Oztechan/CCC#3040] Remove unused common-kermitCrashlytics from root project

---

client/core/res/src/commonMain/resources/MR/base/strings.xml

[Oztechan/CCC#3042] Replace '*' operation with 'x'

---

.github/workflows/project.yml

[Oztechan/CCC#3058] Use reusable flows from the Global repo

---

ios/CCC/Resources/Info.plist

[Oztechan/CCC#2980] Fix iOS app crash due to unsafe url

---

common/core/database/src/jvmMain/kotlin/com/oztechan/ccc/common/core/database/di/CommonCoreDatabaseModule.jvm.kt

[Oztechan/CCC#3087] Move JVM Database to disk

---

.github/workflows/main.yml

[Oztechan/CCC#3093] Move DistributeIOS to ubuntu-latest

---

client/storage/calculation/client-storage-calculation.gradle.kts
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorage.kt
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageImpl.kt
client/storage/calculation/src/commonTest/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageTest.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3120] Move lastInput to Suspend

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorage.kt
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageImpl.kt
client/storage/calculation/src/commonTest/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageTest.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#3123] Move precision to Suspend

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorage.kt
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageImpl.kt
client/storage/calculation/src/commonTest/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageTest.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt

[Oztechan/CCC#3122] Move currentBase to Suspend

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
client/storage/app/client-storage-app.gradle.kts
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorage.kt
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorageImpl.kt
client/storage/app/src/commonTest/kotlin/com/oztechan/ccc/client/storage/app/AppStorageTest.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainSEED.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#3128] Move appTheme to Suspend

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
client/repository/adcontrol/client-repository-adcontrol.gradle.kts
client/repository/adcontrol/src/commonMain/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepository.kt
client/repository/adcontrol/src/commonMain/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryImpl.kt
client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorage.kt
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorageImpl.kt
client/storage/app/src/commonTest/kotlin/com/oztechan/ccc/client/storage/app/AppStorageTest.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesSEED.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainSEED.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
ios/CCC/UI/Main/MainView.swift

[Oztechan/CCC#2942] Move firstRun to Suspend

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
client/repository/adcontrol/src/commonMain/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepository.kt
client/repository/adcontrol/src/commonMain/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryImpl.kt
client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorage.kt
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorageImpl.kt
client/storage/app/src/commonTest/kotlin/com/oztechan/ccc/client/storage/app/AppStorageTest.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#3138] Move premiumEndDate to Suspend

---

client/repository/adcontrol/src/commonMain/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryImpl.kt
client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/repository/appconfig/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepository.kt
client/repository/appconfig/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt
client/repository/appconfig/src/commonTest/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryTest.kt
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorage.kt
client/storage/app/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorageImpl.kt
client/storage/app/src/commonTest/kotlin/com/oztechan/ccc/client/storage/app/AppStorageTest.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt

[Oztechan/CCC#3141] Move sessionCount to Suspend

---

client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/FlowPersistenceImpl.kt
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/SuspendPersistenceImpl.kt
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageImpl.kt
test/src/test/kotlin/com/oztechan/ccc/test/ConventionTest.kt

[Oztechan/CCC#3146] Make implementation classes internal

---

android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#3153] Add test cases for Viewmodel states

---

client/storage/calculation/client-storage-calculation.gradle.kts
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorage.kt
client/storage/calculation/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageImpl.kt
client/storage/calculation/src/commonTest/kotlin/com/oztechan/ccc/client/storage/calculation/CalculationStorageTest.kt

[Oztechan/CCC#3176] Add Flow Property for currentBase

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt
client/viewmodel/selectcurrency/client-viewmodel-selectcurrency.gradle.kts
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencySEED.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/di/ClientViewModelSelectCurrencyModule.kt
client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt
ios/CCC/UI/SelectCurrency/SelectCurrencyRootView.swift

[Oztechan/CCC#3178] Replace CurrencyChange effect with DismissDialog

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesSEED.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/Currencies/CurrenciesRootView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyRootView.swift
ios/CCC/UI/Settings/SettingsRootView.swift
ios/CCC/UI/Slides/BugReportSlideRootView.swift
ios/CCC/UI/Watchers/WatchersRootView.swift

[Oztechan/CCC#3180] Remove ChangeBase Effect

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3183] Remove onBaseChange event

---

android/ui/mobile/src/main/res/navigation/main_graph.xml

[Oztechan/CCC#3148] Remove default destination for Android

---

ios/Gemfile

[Oztechan/CCC#3202] Specify gem versions

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3189] Move to new getBaseFlow logic

---

ios/CCC.xcodeproj/project.pbxproj

[Oztechan/CCC#3235] Use exact versions of SPM dependencies

---

ios/Package.swift

[Oztechan/CCC#3237] Add Package.swift for Renovate

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/Global#3246] Use combine for combining different datasources for calculator

---

gradle/libs.versions.toml

[Oztechan/CCC#3249] Remove compose compiler from TOML

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3251] Prevent multiple Api call when base change on click and add test cases

---

ios/CCC/UI/SelectCurrency/SelectCurrencyRootView.swift
ios/CCC/UI/Watchers/WatcherItem.swift
ios/CCC/UI/Watchers/WatchersView.swift

[Oztechan/CCC#3253] Clean up Swift code

---

gradle/libs.versions.toml

[Oztechan/CCC#3255] Add compose compiler version check into account by its artifact URL

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt

[Oztechan/CCC#3265] Move banners in initView()

---

android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#3272] SearchView crash fix

---

android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#3274] Adjust list item paddings

---

android/ui/mobile/src/main/res/layout/item_settings.xml
android/ui/mobile/src/main/res/values/dimens.xml
android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#3276] Adjust Settings item layout

---

android/ui/mobile/src/main/res/layout/fragment_currencies.xml
android/ui/mobile/src/main/res/values/styles.xml
client/core/res/src/commonMain/resources/MR/base/strings.xml

[Oztechan/CCC#3278] Create common style for bottom info and adjust paddings

---

android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#3280] Adjust SelectCurrencyBar padding

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#3295] Replace macos-latest and ubuntu-latest machines with exact numbers

---

android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#3283] Adjust bottom info layout paddings

---

android/ui/mobile/src/main/res/values/dimens.xml
android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#3285] Increase toolbar text size

---

android/app/src/googleDebug/res/values/strings.xml
android/app/src/huaweiDebug/res/values/strings.xml
ios/CCC.xcodeproj/project.pbxproj

[Oztechan/CCC#3305] Separate app name for debug versions

---

settings.gradle.kts

[Oztechan/CCC#3316] Update Gradle enterprise to 3.17.X

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#3327] Migrate to Gradle build action V3 syntax

---

.github/workflows/main.yml
.github/workflows/release.yml
settings.gradle.kts

[Oztechan/CCC#3329] Get rid of gradle enterprise plugin and activate build scan in CI

---

android/app/src/main/kotlin/com/oztechan/ccc/android/app/Application.kt
android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/Ads.kt
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/Ads.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt

[Oztechan/CCC#3342] Move Ad initialization into Activity

---

.github/workflows/main.yml

[Oztechan/CCC#3348] Don't cancel develop builds when there is a new build

---

android/core/ad/android-core-ad.gradle.kts
android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/Ads.kt
gradle/libs.versions.toml

[Oztechan/CCC#3352] Add Google UMP and CMP logic for Android

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#3361] Minor version update

---

gradle.properties

[Oztechan/CCC#3391] Add enableJetifier for android builds

---

gradle.properties

[Oztechan/CCC#3399] Improve Kotlin Gradle properties

---

.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#3401] Remove token from delete artifact job

---

android/core/ad/src/google/AndroidManifest.xml

[Oztechan/CCC#3406] Fix AD_SERVICES_CONFIG duplication for android gradle plugin

---

CCC.gradle.kts
android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

[Oztechan/CCC#3413] Move compose dependencies to Compose Multiplatform

---

gradle/libs.versions.toml

[Oztechan/CCC#3417] Update Kotlin to 1.9.23

---

android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#3419] Replace android compose dependencies with the Compose Multiplatform one

---

android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#3422] Replace android navigation with CMP navigation

---

settings.gradle.kts

[Oztechan/CCC#3453] Remove unnecessary settings.gradle urls

---

.github/workflows/copy-secrets.yml

[Oztechan/CCC#3465] Create workflow for copying the secrets for dependabot

---

client/configservice/ad/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/ad/AdConfigServiceImpl.kt
client/configservice/review/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/review/ReviewConfigServiceImpl.kt
client/configservice/update/src/commonMain/kotlin/com/oztechan/ccc/client/configservice/update/UpdateConfigServiceImpl.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/error/NonParsableStringException.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/util/Parser.kt
client/core/remoteconfig/src/commonTest/kotlin/com/oztechan/ccc/client/core/remoteconfig/util/ParserTest.kt

[Oztechan/CCC#3457] Add runCaching and NonParsableString Exception to RemoteConfig layer

---

client/core/persistence/client-core-persistence.gradle.kts
client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceImpl.kt

[Oztechan/CCC#3459] Add logging to persistence layer

---

client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceImpl.kt
client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/util/Parser.kt
common/core/database/src/commonMain/kotlin/com/oztechan/ccc/common/core/database/base/BaseDBDataSource.kt
common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/base/BaseNetworkService.kt

[Oztechan/CCC#3478] First log and then throw the exceptions

---

CCC.gradle.kts

[Oztechan/CCC#3480] Replace kotlinOptions with compileOptions

---

android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#3476] Remove non-working Search View crash workaround

---

android/core/billing/src/google/kotlin/com/oztechan/ccc/android/core/billing/BillingManagerImpl.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/slider/SliderFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/Dialog.kt
client/repository/appconfig/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt

[Oztechan/CCC#3490] Update ScopeMob Higher-order functions and lambdas to use lambdas

---

gradle.properties

[Oztechan/CCC#3498] Remove Kotlin Multiplatform stability warning suppression

---

.gitignore

[Oztechan/CCC#3501] Add missed .gitignore filesAdd missed .gitignore folders

---

ios/CCC/Application.swift

[Oztechan/CCC#3505] Mute video ads for iOS

---

gradle.properties

[Oztechan/CCC#3503] Add Kotlin build reports to Gradle build scans and text file

---

ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved

[Oztechan/CCC#3507] Update Swift packages to latest versions

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt

[Oztechan/CCC#3510] Track exception for destination not found

---

gradle/libs.versions.toml

[Oztechan/CCC#3538] Update androidGradlePlugin to 8.4.2

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#3555] Replace executions with provider based methods

---

CCC.gradle.kts

[Oztechan/CCC#3562] Make Detekt tasks Gradle configuration cache friendly

---

gradle.properties

[Oztechan/CCC#3554] Enable Gradle configuration cache

---

client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt

[Oztechan/CCC#3571] Temporary comment the failed test case

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencySEED.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt

[Oztechan/CCC#3585] Remove SelectCurrencyFragment navigation result logic

---

client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt

[Oztechan/CCC#3578] Add back ifUserPropertiesSetCorrect in MainViewModelTest

---

client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt

[Oztechan/CCC#3607] Add back session count test case

---

.github/workflows/main.yml
.github/workflows/project.yml
.github/workflows/publish.yml
.github/workflows/release.yml

[Oztechan/CCC#3612] Use develop has for Global repo for decreasing manual work

---

.github/workflows/main.yml

[Oztechan/CCC#3616] Separate Check and Coverage

---

.github/workflows/main.yml

[Oztechan/CCC#3618] Exclude Check job from Slack notification check when the branch is develop

---

.github/workflows/main.yml

[Oztechan/CCC#3614] Upload debug version of app into Firebase app distribution

---

.github/actions/add-secret-files/action.yml
.github/workflows/main.yml
.github/workflows/release.yml
.gitignore

[Oztechan/CCC#3628] Update android keystore

---

.github/workflows/main.yml

[Oztechan/CCC#3634] Add also the release apks in Firebase App Distribution

---

client/datasource/currency/client-datasource-currency.gradle.kts
client/datasource/currency/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/currency/CurrencyDataSourceTest.kt
client/datasource/watcher/client-datasource-watcher.gradle.kts
client/datasource/watcher/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/watcher/WatcherDataSourceTest.kt
common/datasource/conversion/common-datasource-conversion.gradle.kts
common/datasource/conversion/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/conversion/ConversionDataSourceTest.kt

[Oztechan/CCC#3582] Add back the DataSource Test Cases

---

.github/workflows/main.yml

[Oztechan/CCC#3636] Adjust workflow to not cancel previous builds when the branch is develop

---

client/repository/adcontrol/src/commonTest/kotlin/com/oztechan/ccc/client/repository/adcontrol/AdControlRepositoryTest.kt

[Oztechan/CCC#3580] Add back commented AdControlRepositoryTest test case

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt

[Oztechan/CCC#3632] Add missed lifecycle logs

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt

[Oztechan/CCC#3638] Add back navigation result logic

---

ios/CCC/Resources/Info.plist

[Oztechan/CCC#3640] Update SKAdNetworkItems

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#3642] Fix iOS App versioning

---

.github/workflows/release.yml

[Oztechan/CCC#3644] Add missed checkout before using composite action

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#3647] Fix agvtool output error

---

.github/workflows/main.yml

[Oztechan/CCC#3651] Enable back Check task in develop for caching

---

.github/workflows/main.yml
ios/Gemfile
ios/fastlane/Fastfile

[Oztechan/CCC#3649] Run both iOS configurations in PR jobs

---

client/core/res/client-core-res.gradle.kts

[Oztechan/CCC#2579] Remove moko detekt task dependency

---

client/core/res/client-core-res.gradle.kts

[Oztechan/CCC#2580] Remove additional srcDirs for android

---

android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#3662] Move androidx.navigation.safeargs to kotlin version

---

android/ui/mobile/android-ui-mobile.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#3666] Update Google Play Core to Core Review

---

.github/workflows/main.yml

[Oztechan/CCC#3673]  Run develop Job every day

---

.github/workflows/main.yml
ios/fastlane/Fastfile

[Oztechan/CCC#3654] Upload both configurations of iOS app to Firebase app distribution

---

.github/workflows/main.yml

[Oztechan/CCC#3669] Add lint task in CodeAnalysis job

---

.github/workflows/main.yml

[Oztechan/CCC#3671] Replace Check job with Test

---

.github/workflows/main.yml

[Oztechan/CCC#3679] Upload builds to Firebase on schedule

---

.github/workflows/main.yml

[Oztechan/CCC#3682] Move GradleBuild to Release/Debug Variants based of event

---

.github/workflows/main.yml

[Oztechan/CCC#3695] Fix develop builds cancellation issue

---

.github/workflows/main.yml

[Oztechan/CCC#3693] Fix iOS fastlane build issue

---

.github/workflows/main.yml

[Oztechan/CCC#3691] Fix wrong Notify issue

---

.github/workflows/main.yml

[Oztechan/CCC#3697] Fix step names

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/core/viewmodel/SEEDViewModel.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
ios/CCC/Util/ObservableSEEDViewModel.swift

Resolves Oztechan/CCC#ISSUE_ID

[Oztechan/CCC#3714] Move Effect into SEEDViewModel

---

android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/core/viewmodel/SEEDViewModel.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt

[Oztechan/CCC#3727] Create sendEffect method for fire and forget

---

client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt
client/viewmodel/settings/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModelTest.kt

[Oztechan/CCC#3745] add assertNotNull for firstOrNull() test cases

---

android/core/billing/src/google/kotlin/com/oztechan/ccc/android/core/billing/BillingManagerImpl.kt

[Oztechan/CCC#3747] Remove offer token for one time purchases

---

android/core/billing/src/google/kotlin/com/oztechan/ccc/android/core/billing/mapper/PurchaseMapper.kt
android/core/billing/src/main/kotlin/com/oztechan/ccc/android/core/billing/model/Purchase.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/PurchaseUtil.kt
android/ui/mobile/src/test/kotlin/com/oztechan/ccc/android/ui/mobile/util/PurchaseUtilTest.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/model/OldPurchase.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt

[Oztechan/CCC#3751] Add purchaseToken into custom Purchase Model

---

android/core/billing/src/google/kotlin/com/oztechan/ccc/android/core/billing/BillingManagerImpl.kt
android/core/billing/src/huawei/kotlin/com/oztechan/ccc/android/core/billing/BillingManagerImpl.kt
android/core/billing/src/main/kotlin/com/oztechan/ccc/android/core/billing/BillingManager.kt

[Oztechan/CCC#3753] Add consume purchase methods to BillingManager

---

client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt

[Oztechan/CCC#3785] Implement Consume product logic

---

client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt

[Oztechan/CCC#3787] Cover Restore and Consume Product logic

---

ios/CCC/Application.swift
ios/CCC/UI/Main/MainRootView.swift

[Oztechan/CCC#3803] Clean Application class and move view related things into MainView

---

ios/CCC/UI/Main/MainScene.swift

[Oztechan/CCC#3812] Move onPause and onResume into onScenePhaseChange

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainSEED.kt
client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
client/viewmodel/main/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModelTest.kt
ios/CCC/UI/Main/MainScene.swift

[Oztechan/CCC#3814] Refactor onResume/Pause logic with foreground/background

---

ios/CCC/UI/Main/MainScene.swift

[Oztechan/CCC#3816] Prevent double onAppBackground calls

---

android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#3864] Replace usages of abc_textfield_search_material with null

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt

[Oztechan/CCC#3872] Remove set and get navigation results

---

ios/CCC/UI/Calculator/CalculatorRootView.swift

[Oztechan/CCC#3883] Move iOS Calculator Screen to onSheetDismissed logic

---

client/viewmodel/selectcurrency/client-viewmodel-selectcurrency.gradle.kts
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/di/ClientViewModelSelectCurrencyModule.kt
client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt

[Oztechan/CCC#3884] Set base currency when SelectCurrencySheet item is clicked

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyAdapter.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencySEED.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/model/SelectCurrencyPurpose.kt
client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt
ios/CCC/UI/Calculator/CalculatorRootView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyRootView.swift
ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
ios/CCC/UI/Watchers/WatchersRootView.swift

[Oztechan/CCC#3897] Introduce SelectCurrencyPurpose

---

gradle/wrapper/gradle-wrapper.properties

[Oztechan/CCC#3899] Downgrade Gradle to 8.9

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt

[Oztechan/CCC#3910] Always track currentBase change

---

android/viewmodel/widget/android-viewmodel-widget.gradle.kts
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/di/AndroidViewModelWidgetModule.kt
android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt

[Oztechan/CCC#3914] Track currentBase change in widget

---

android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3916] Ensure that base changes happens only once

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt

[Oztechan/CCC#3923] Read base from states whenever possible

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt

[Oztechan/CCC#3925] Avoid updating output when not needed

---

client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3919] Add test for order of calls after currency change and the conversion calculation

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt

[Oztechan/CCC#3927] Read precision once in calculateConversions

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3929] Extract updating the symbol into new method

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt

[Oztechan/CCC#3931] Simplify currentBaseChanged logic and add more test case

---

client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt

[Oztechan/CCC#3933] Move loadings into beginning of observations

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/watchers/WatcherItem.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/watchers/WatchersView.kt
client/datasource/watcher/src/commonMain/kotlin/com/oztechan/ccc/client/datasource/watcher/mapper/WatcherMapper.kt
client/datasource/watcher/src/commonTest/kotlin/com/oztechan/ccc/client/datasource/watcher/mapper/WatcherMapperTest.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt
client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
client/viewmodel/watchers/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModelTest.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/Watcher.kt
ios/CCC/UI/Watchers/WatcherItem.swift
ios/repository/background/src/commonMain/kotlin/com/oztechan/ccc/ios/repository/background/BackgroundRepositoryImpl.kt
ios/repository/background/src/commonTest/kotlin/com/oztechan/ccc/ios/repository/background/BackgroundRepositoryTest.kt

[Oztechan/CCC#3937] Rename remaining watcher bases with sources

---

.github/workflows/main.yml

[Oztechan/CCC#3944] Upload iOS Debug dSYM to Firebase

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt

[Oztechan/CCC#3948] Replace restartApp logic with recreate()

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt

[Oztechan/CCC#3950] Add restartActivity method with Intent flags

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#3952] Increase Target SDK

---

gradle.properties

[Oztechan/CCC#3965] Update gradle properties GitHub Action friendly way

---

backend/app/src/main/resources/application.conf

[Oztechan/CCC#3979] Open 80 port for backend app

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/CurrencyRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/ErrorRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/RootRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/VersionRoute.kt

[Oztechan/CCC#3980] Remove suspends from ktor methods

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/VersionRoute.kt

[Oztechan/CCC#3983] Get rid of unsafe version read

---

.github/workflows/main.yml

[Oztechan/CCC#3993] Fix Firebase Distribution uploading step for fastlane

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/module/APIModule.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/CurrencyRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/ErrorRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/RootRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/VersionRoute.kt

[Oztechan/CCC#3991] Rename routes

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/module/APIModule.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/CurrencyRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/ErrorRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/RootRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/VersionRoute.kt

[Oztechan/CCC#3995] Use injections inside the routes

---

android/ui/mobile/src/main/res/values/dimens.xml
android/ui/mobile/src/main/res/values/styles.xml

[Oztechan/CCC#4081] Set fixed size for banner ad container

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt

[Oztechan/CCC#4085] Hide the unused area when ads are not visible

---

buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#4095] Remove UnstableApiUsage

---

android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt

[Oztechan/CCC#4098] Add Logs for banner ad failed requests for Android

---

android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
ios/CCC/UI/Components/AdaptiveBannerAdView.swift

[Oztechan/CCC#4100] Add Logs for banner ad failed requests for iOS

---

android/core/ad/src/google/AndroidManifest.xml

[Oztechan/CCC#3544] Remove AD_SERVICES_CONFIG resource replacement

---

.github/workflows/build.yml
.github/workflows/main.yml
.github/workflows/release.yml

[Oztechan/CCC#4164] Move to macos-15 runners

---

ios/CCC/Util/ViewExt.swift

[Oztechan/CCC#4179] Fix sticky Snackbar issue

---

ios/CCC.xcodeproj/project.pbxproj
ios/CCC/Application.swift

[Oztechan/CCC#4189] Configure Firebase and Crashlytics only in CI builds

---

android/ui/mobile/android-ui-mobile.gradle.kts
client/configservice/ad/client-configservice-ad.gradle.kts
client/configservice/review/client-configservice-review.gradle.kts
client/configservice/update/client-configservice-update.gradle.kts
client/core/remoteconfig/client-core-remoteconfig.gradle.kts
client/repository/adcontrol/client-repository-adcontrol.gradle.kts
client/repository/appconfig/client-repository-appconfig.gradle.kts
client/viewmodel/calculator/client-viewmodel-calculator.gradle.kts
client/viewmodel/currencies/client-viewmodel-currencies.gradle.kts
client/viewmodel/main/client-viewmodel-main.gradle.kts
client/viewmodel/settings/client-viewmodel-settings.gradle.kts
client/viewmodel/watchers/client-viewmodel-watchers.gradle.kts

[Oztechan/CCC#4235] Enable Desugaring in the modules that using remote config directly or indirectly

---

ios/CCC/Application.swift
ios/CCC/Resources/GoogleService-Info.plist

[Oztechan/CCC#4233] Update dummy GooglePlist with somethings that works

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt

[Oztechan/CCC#4237] Use the KTX extension function String.toUri

---

client/core/shared/src/commonMain/kotlin/com/oztechan/ccc/client/core/shared/model/AppTheme.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/util/PremiumUtil.kt
ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved

[Oztechan/CCC#4249] Replace MagicNumbers with named arguments and constants

---

buildSrc/src/main/kotlin/ProjectSettings.kt
ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved

[Oztechan/CCC#4251] Update Minor version to 11

---

backend/app/backend-app.gradle.kts
common/core/network/common-core-network.gradle.kts
gradle/libs.versions.toml

[Oztechan/CCC#4253] Re-structure client and server dependencies

---

backend/app/src/main/resources/application.conf

[Oztechan/CCC#4289] Use single 8080 port by default

---

.aiexclude

[Oztechan/CCC#4306] add aiexclude file for gemini

---

ios/CCC.xcodeproj/project.pbxproj
ios/Package.swift

[Oztechan/CCC#4322] Revert wrong SDK update

---

android/core/ad/android-core-ad.gradle.kts
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt
client/core/shared/src/commonMain/kotlin/com/oztechan/ccc/client/core/shared/model/AppTheme.kt
client/core/shared/src/commonTest/kotlin/com/oztechan/ccc/client/core/shared/model/AppThemeTest.kt
client/core/shared/src/commonTest/kotlin/com/oztechan/ccc/client/core/shared/util/RateUtilTest.kt
client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/model/PremiumType.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModelTest.kt
client/viewmodel/premium/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/premium/model/PremiumTypeTest.kt
common/core/model/src/commonMain/kotlin/com/oztechan/ccc/common/core/model/CurrencyType.kt

[Oztechan/CCC#2504] Replace enum values() with entries

---

CCC.gradle.kts

[Oztechan/CCC#4392] Remove combined dependency task

---

android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt
android/ui/mobile/src/main/res/values/styles.xml
buildSrc/src/main/kotlin/ProjectSettings.kt

[Oztechan/CCC#4256] Add support for Android 15

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/CurrencyRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/ErrorRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/RootRoute.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/VersionRoute.kt

[Oztechan/CCC#4404] Remove dispatchers and scopes from backend Routes

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/Application.kt

[Oztechan/CCC#4411] Open 80 port in CI builds

---

backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/Application.kt
backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/util/EnvironmentExt.kt

[Oztechan/CCC#4487] Refactor CI environment logic with Production
