- build.gradle.kts
- buildSrc/src/main/kotlin/SecretExt.kt
- gradle/libs.versions.toml
> [Oztechan/CCC#1717] Remove dependency updates library

- .github/workflows/project.yml
> [Oztechan/CCC#2098] Add PR automations

- .github/workflows/project.yml
> [Oztechan/CCC#2676] Automatically move dependency PR by renovate to PR Review and assign current iteration

- client/core/persistence/src/androidMain/kotlin/com/oztechan/ccc/client/core/persistence/di/ClientCorePersistenceModule.android.kt
- client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/SuspendPersistence.kt
- client/core/persistence/src/commonMain/kotlin/com/oztechan/ccc/client/core/persistence/SuspendPersistenceImpl.kt
- client/core/persistence/src/iosMain/kotlin/com/oztechan/ccc/client/core/persistence/di/ClientCorePersistenceModule.ios.kt
> [Oztechan/CCC#2857] Add Suspension support for multiplatform settings

- client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/PersistenceTest.kt
- client/core/persistence/src/commonTest/kotlin/com/oztechan/ccc/client/core/persistence/fakes/Fakes.kt
> [Oztechan/CCC#2860] Move common test values to Fakes in order to share

- CCC.gradle.kts
- android/app/android-app.gradle.kts
- gradle/libs.versions.toml
> [Oztechan/CCC#2929] Get rid of firebasePerPlugin classpath

- android/app/src/main/kotlin/com/oztechan/ccc/android/app/Application.kt
> [Oztechan/CCC#3309] Enable Crashlytics only in release mode

- .github/workflows/main.yml
- .github/workflows/release.yml
> [Oztechan/CCC#3404] Move project to Setup Gradle Repo from Global repo

- android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
- android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/IntentUtil.kt
- client/core/remoteconfig/src/commonMain/kotlin/com/oztechan/ccc/client/core/remoteconfig/util/Parser.kt
- ios/CCC/Util/InterstitialAd.swift
- ios/CCC/Util/RewardedAd.swift
- ios/repository/background/src/commonMain/kotlin/com/oztechan/ccc/ios/repository/background/BackgroundRepositoryImpl.kt
> [Oztechan/CCC#3442] Add new instance of exceptions to logging

- common/core/database/common-core-database.gradle.kts
- common/core/database/src/commonMain/kotlin/com/oztechan/ccc/common/core/database/base/BaseDBDataSource.kt
- common/core/network/common-core-network.gradle.kts
- common/core/network/src/commonMain/kotlin/com/oztechan/ccc/common/core/network/base/BaseNetworkService.kt
> [Oztechan/CCC#3444] Add logging to API and Database layers

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt
> [Oztechan/CCC#3482] Set and Get navigation results according to destination's backstacks

- .github/actions/add-secret-files/action.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> [Oztechan/CCC#3541] Create a composite action for Adding secret files

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
- client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
> [Oztechan/CCC#3592] Use the currentBase stored in preference at onResume

- ios/CCC.xcodeproj/project.pbxproj
- ios/fastlane/Appfile
- ios/fastlane/Fastfile
> [Oztechan/CCC#3656] Add debug postfix to the bundle identifier of iOS app

- android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
- client/core/viewmodel/src/commonMain/kotlin/com/oztechan/ccc/client/core/viewmodel/SEEDViewModel.kt
- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
- client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
- client/viewmodel/main/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
- client/viewmodel/premium/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt
- client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
- client/viewmodel/settings/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt
- client/viewmodel/watchers/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
- ios/CCC/Util/ObservableSEEDViewModel.swift
> [Oztechan/CCC#3717] Move Event into SEEDViewModel

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/main/MainActivity.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/premium/PremiumBottomSheet.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt
- client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt
> [Oztechan/CCC#3719] Name all the ViewModels as viewmodel

- android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
> [Oztechan/CCC#3729] Simplify WidgetViewModel

- ios/CCC/UI/Calculator/CalculatorView.swift
- ios/CCC/UI/Calculator/ConversionStateView.swift
- ios/CCC/UI/Calculator/InputView.swift
- ios/CCC/UI/Calculator/OutputView.swift
- ios/CCC/UI/Currencies/CurrenciesView.swift
- ios/CCC/UI/Watchers/WatchersRootView.swift
> [Oztechan/CCC#3819] Update deprecated animation to iOS 15 friendly way

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyBottomSheet.kt
> [Oztechan/CCC#3870] Remove CurrenciesFragment navigation result logic

- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
> [Oztechan/CCC#3878] Create onSheetDismissed Event for CalculatorViewModel

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
> [Oztechan/CCC#3882] Move Android Calculator Screen to onSheetDismissed logic

- client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
> [Oztechan/CCC#3880] Cover onSheetDismissed Event for CalculatorViewModel

- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
- client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
- ios/CCC/UI/Calculator/CalculatorRootView.swift
- ios/CCC/UI/Currencies/CurrenciesRootView.swift
- ios/CCC/UI/SelectCurrency/SelectCurrencyRootView.swift
- ios/CCC/UI/Settings/SettingsRootView.swift
- ios/CCC/UI/Slides/BugReportSlideRootView.swift
- ios/CCC/UI/Watchers/WatchersRootView.swift
> [Oztechan/CCC#3888] Remove onBaseChange event

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
- client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesSEED.kt
- client/viewmodel/currencies/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
- client/viewmodel/currencies/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModelTest.kt
> [Oztechan/CCC#3891] Remove ChangeBase Event from Currencies Screen

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/selectcurrency/SelectCurrencyAdapter.kt
- client/viewmodel/selectcurrency/client-viewmodel-selectcurrency.gradle.kts
- client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt
- client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/di/ClientViewModelSelectCurrencyModule.kt
- client/viewmodel/selectcurrency/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/model/SelectCurrencyPurpose.kt
- client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt
- ios/CCC/UI/Calculator/CalculatorRootView.swift
- ios/CCC/UI/Watchers/WatcherItem.swift
- ios/CCC/UI/Watchers/WatchersRootView.swift
- ios/CCC/UI/Watchers/WatchersView.swift
> [Oztechan/CCC#3903] Move WatchersScreen to SelectCurrencyPurpose

- client/viewmodel/selectcurrency/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModelTest.kt
> [Oztechan/CCC#3907] Cover different SelectCurrencyPurposes onItemClick

- android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/HeaderView.kt
- android/ui/widget/src/main/kotlin/com/oztechan/ccc/android/ui/widget/content/WidgetView.kt
- android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetSEED.kt
- android/viewmodel/widget/src/main/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModel.kt
- android/viewmodel/widget/src/test/kotlin/com/oztechan/ccc/android/viewmodel/widget/WidgetViewModelTest.kt
- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
> [Oztechan/CCC#3912] Rename Widget currentBase states to base

- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
> [Oztechan/CCC#3921] Update observed persisted values only inside observation block

- client/viewmodel/calculator/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
- client/viewmodel/calculator/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModelTest.kt
> [Oztechan/CCC#3935] Move onBaseChanged into base observation

- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/IntentUtil.kt
> [Oztechan/CCC#3954] Update resolveAndStartIntent with more error prone approach

- backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/module/APIModule.kt
- backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/CurrencyRoute.kt
- backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/ErrorRoute.kt
- backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/RootRoute.kt
- backend/app/src/main/kotlin/com/oztechan/ccc/backend/app/routes/VersionRoute.kt
> [Oztechan/CCC#3996] Move threading into Routes

- android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
- android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
- android/core/ad/src/main/kotlin/com/oztechan/ccc/android/core/ad/AdManager.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/calculator/CalculatorFragment.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/currencies/CurrenciesFragment.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/content/settings/SettingsFragment.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt
> [Oztechan/CCC#4083] Remove onAdLoaded listener and use predefined fixed height

- android/core/ad/src/google/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
- android/core/ad/src/huawei/kotlin/com/oztechan/ccc/android/core/ad/AdManagerImpl.kt
- android/core/ad/src/main/kotlin/com/oztechan/ccc/android/core/ad/AdManager.kt
- android/ui/mobile/src/main/kotlin/com/oztechan/ccc/android/ui/mobile/util/ViewExtensions.kt
> [Oztechan/CCC#4087] Move exact height calculation into AdManager
