Oztechan/CCC

app/src/main/java/mustafaozhan/github/com/mycurrencies/base/viewmodel/BaseDataViewModel.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/function/extension/ViewExtension.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/function/lambda/OptionalLambda.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/ui/main/fragment/calculator/CalculatorAdapter.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/ui/main/fragment/calculator/CalculatorFragment.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/ui/main/fragment/calculator/CalculatorViewModel.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/ui/main/fragment/calculator/CalculatorViewState.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/ui/main/fragment/settings/SettingsFragment.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/ui/main/fragment/settings/SettingsViewModel.kt, app/src/main/java/mustafaozhan/github/com/mycurrencies/ui/main/fragment/settings/SettingsViewState.kt, app/src/main/res/layout/fragment_calculator.xml, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values/strings.xml, build.gradle, dependencies.gradle, gradle/wrapper/gradle-wrapper.properties
=> Adding empty view State

.github/workflows/board.yml
=> [#163] Project Automations workflow added

docs/ISSUE_TEMPLATE.md, docs/PULL_REQUEST_TEMPLATE.md
=> [#166] PULL_REQUEST_TEMPLATE.md and ISSUE_TEMPLATE.md added

docs/CONTRIBUTING.md, docs/ISSUE_TEMPLATE.md, docs/PULL_REQUEST_TEMPLATE.md
Added CONTRIBUTING.md file in order to guide new PRs
=> [#169] CONTRIBUTING.md file added

backend/src/jvmMain/kotlin/com/github/mustafaozhan/ccc/backend/BackendApp.kt
increasing backend request queue and running limit
Resolves #171 
* [] I have read the [guidelines for contributing](https://github.com/Oztechan/CCC/blob/develop/docs/CONTRIBUTING.md)
* [] I have tested the app before creating this PR
* [] PR title starts with `[#ISSUE_ID]`
* [] I have added a valid description and it ends with `Resolves: #ISSUE_ID`
=> [#171] increasing backend request queue and running limit

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#181] minor version raise

.github/workflows/main.yml, .github/workflows/release.yml
replace not necessary macos-latest jobs with ubuntu-latest
Resolves #190
=> [#190] replace not necessary macos-latest jobs with ubuntu-latest

.github/workflows/board.yml
make board automations single job
Resolves #188
=> [#188] make board automations single job

client/src/mobileMain/resources/MR/base/strings.xml
change developer email Resolves #187
=> [#187] change developer email

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, billing/src/google/java/com/github/mustafaozhan/billing/BillingManagerImpl.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/adremove/AdRemoveSEED.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/AdRemoveViewModelTest.kt
=> [#176] restarting app after restoring purchase in order to remove ads

.github/CODEOWNERS
=> [#203] adding CoreTeam into code owners

codecov.yml
=> [#208] adding codecov.yml to project

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/model/RemoveAdType.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/util/Extensions.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt
=> [#196] adding life time purchase

buildSrc/src/main/kotlin/Versions.kt, gradle/wrapper/gradle-wrapper.properties
gradle and library updates
Resolves #215
=> [#215] gradle and library updates

android/src/main/java/com/github/mustafaozhan/ccc/android/app/CCCApplication.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, billing/src/google/java/com/github/mustafaozhan/billing/BillingManagerImpl.kt, billing/src/huawei/java/com/github/mustafaozhan/billing/BillingManagerImpl.kt, billing/src/main/kotlin/com/github/mustafaozhan/billing/BillingManager.kt, buildSrc/src/main/kotlin/Versions.kt, gradle/wrapper/gradle-wrapper.properties
Replace billing client with private variable and initialize crashlytics earlier
Resolves #218
=> #218 Replace billing client with private variable

backend/src/jvmMain/kotlin/com/github/mustafaozhan/ccc/backend/BackendApp.kt, backend/src/jvmMain/kotlin/com/github/mustafaozhan/ccc/backend/controller/ApiController.kt
=> [#221] Increase Backend thread pool, number of threads and number of refresh in a day

android/src/main/java/com/github/mustafaozhan/ccc/android/app/CCCApplication.kt
=> [#210] Remove Watchdog for API 11 and above

ad/src/google/java/com/github/mustafaozhan/ad/AdManagerImpl.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
=> [#217] LogMobWriter exception differentiation

backend/src/jvmMain/kotlin/com/github/mustafaozhan/ccc/backend/controller/ApiController.kt, buildSrc/src/main/kotlin/BuildValues.kt, common/build.gradle.kts, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/api/ApiRepository.kt, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/api/ApiRepositoryImpl.kt, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/api/ApiService.kt, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/model/CurrencyType.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/ApiRepositoryTest.kt
=> [#229] More accurate fetching for popular currencies with a new API

docs/PULL_REQUEST_TEMPLATE.md
=> [#206] PR template fix

docs/ISSUE_TEMPLATE.md
=> [#234] updating issue template

.github/workflows/main.yml, build.gradle.kts, codecov.yml
=> [#185] Codecov reporting Improvments

analytics/src/main/java/com/mustafaozhan/github/analytics/AnalyticsManager.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/AnalyticsManagerImpl.kt, android/src/main/AndroidManifest.xml, android/src/main/java/com/github/mustafaozhan/ccc/android/di/PlatformModule.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/bar/BarBottomSheet.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/slider/SliderFragment.kt
=> [#239] Tracking screen views

analytics/build.gradle.kts, analytics/src/main/java/com/mustafaozhan/github/analytics/AnalyticsManager.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/AnalyticsManagerImpl.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/model/UserProperty.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/util/AnalyticsUtil.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/di/PlatformModule.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/main/MainActivity.kt, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/model/AppTheme.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/calculator/CalculatorSEED.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [#240] User Property Tracking

analytics/src/main/java/com/mustafaozhan/github/analytics/model/UserProperty.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt
=> [#246] Add currency_count to user properties

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/main/MainActivity.kt
=> [#249] minimise multiple tracking

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt
=> [#251] set user property for only active currencies

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt
=> [#253] calculateAdRewardEnd test case fix and removing deprecated duration

.github/workflows/main.yml, buildSrc/src/main/kotlin/Versions.kt, codecov.yml
=> [#254] update cover and new generated reports

analytics/src/main/java/com/mustafaozhan/github/analytics/AnalyticsManager.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/AnalyticsManagerImpl.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/model/EventParam.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/model/FirebaseEvent.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorAdapter.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/changebase/ChangeBaseBottomSheet.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt
=> [#241] add event tracking

analytics/src/main/java/com/mustafaozhan/github/analytics/model/EventParam.kt, analytics/src/main/java/com/mustafaozhan/github/analytics/model/FirebaseEvent.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorAdapter.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/changebase/ChangeBaseBottomSheet.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt, codecov.yml
=> [#259] track conversion show

analytics/src/main/java/com/mustafaozhan/github/analytics/model/FirebaseEvent.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/settings/SettingsFragment.kt, codecov.yml
=> [#260] track offline sync

android/build.gradle.kts, buildSrc/src/main/kotlin/Extensions.kt, buildSrc/src/main/kotlin/config/BuildValues.kt, buildSrc/src/main/kotlin/config/Keys.kt, common/build.gradle.kts
=> [#226] Better organising compile time values

buildSrc/src/main/kotlin/ProjectSettings.kt, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/api/ApiService.kt
=> [#274] Version Increase

common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/api/ApiService.kt
=> [#279] API path update

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/main/MainActivity.kt, android/src/main/res/layout/activity_main.xml
=> [#282] Navigation duplication fix

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/slider/SliderFragment.kt
=> [#286] Analytics Null Screen name fix

common/build.gradle.kts
=> [#289] fix Native tests

.github/workflows/main.yml, common/build.gradle.kts
=> [#285] move Kover task to macOS

README.md
=> [#296] Codacy README.md issues

README.md
=> [#298] Fix README.md issues

analytics/build.gradle.kts, analytics/src/main/java/com/mustafaozhan/github/analytics/util/AnalyticsUtil.kt, build.gradle.kts
=> [#304] Disable hms until build issue fixed

analytics/build.gradle.kts, analytics/src/main/java/com/mustafaozhan/github/analytics/util/AnalyticsUtil.kt, build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
=> [#306] Simplify JS definitions

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/base/BaseViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/mapper/CurrencyTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/util/Extension.kt
=> [#308] Add client module mapper tests

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/mapper/CurrencyTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/mapper/OfflineRatesTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/mapper/RatesTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/util/TestUtil.kt
=> [#310] add Rates and OfflineRates tests

.github/workflows/main.yml, build.gradle.kts, buildSrc/src/main/kotlin/config/DeviceFlavour.kt
=> [#294] merge Kover and gradle jobs

README.md
=> [#314] update README.md

common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/mapper/Currency.kt, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/util/KtorLogger.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/mapper/CurrencyResponseTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/mapper/CurrencyTest.kt
=> [#313] Add tests for Currency and CurrencyResponse mappers

analytics/build.gradle.kts, analytics/src/main/java/com/mustafaozhan/github/analytics/util/AnalyticsUtil.kt, build.gradle.kts
=> [#303] hms build issue fix

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/util/Extension.kt, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/mapper/Currency.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/mapper/CurrencyTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/mapper/OfflineRatesTest.kt
=> [#317] Mapper and test improvement

.github/workflows/main.yml
=> [#320] Fix wrong CI notification

gradle/wrapper/gradle-wrapper.properties
=> [#322] Gradle update

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, client/build.gradle.kts, common/build.gradle.kts
=> [#257] Add mockative

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/AdRemoveViewModelTest.kt
=> [#329] AdRemoveViewModel with mocks

android/src/main/java/com/github/mustafaozhan/ccc/android/app/CCCApplication.kt, backend/src/jvmMain/kotlin/com/github/mustafaozhan/ccc/backend/BackendApp.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/base/BaseViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/iosMain/kotlin/com/github/mustafaozhan/ccc/client/Logger.kt, common/build.gradle.kts, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/ApiRepositoryTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/SettingsRepositoryTest.kt
=> [#330] CalculatorViewModel with mocks

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/ChangeBaseViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#333] move all viewModels to mocking

buildSrc/src/main/kotlin/Versions.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/di/Koin.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainSEED.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/iosMain/kotlin/com/github/mustafaozhan/ccc/client/di/KoinIOS.kt
=> [#339] increase coverage MainViewModel

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/ChangeBaseViewModelTest.kt
=> [#343] increase coverage ChangeBaseViewModel

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/util/Extensions.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt
=> [#347] increase coverage in Client Extensions

common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/api/repo/ApiRepositoryImpl.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/ApiRepositoryTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/util/ResultTest.kt
=> [#350] increase ApiRepository coverage

README.md
=> [#355] Update README.md badges

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/SettingsRepositoryTest.kt
=> [#351] increase coverage in SettingsRepository

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/ChangeBaseViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/ApiRepositoryTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/SettingsRepositoryTest.kt
=> [#359] Add missed verifies

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/ChangeBaseViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#357] Increase coverage CurrenciesViewModel

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/model/RemoveAdTypeTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/AdRemoveViewModelTest.kt
=> [#361] increase coverage AdRemoveViewModel

ad/src/google/java/com/github/mustafaozhan/ad/AdManagerImpl.kt, ad/src/huawei/java/com/github/mustafaozhan/ad/AdManagerImpl.kt, ad/src/main/java/com/github/mustafaozhan/ad/AdManager.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/util/Extension.kt
=> [#168] Banner Animation

README.md
=> [#368] Remove Codebeat

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/util/Extensions.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#364] increase coverage SettingsViewModel

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/changebase/ChangeBaseBottomSheet.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt, billing/src/google/java/com/github/mustafaozhan/billing/BillingManagerImpl.kt
=> [#212] Check possible lazy implementations

gradle/wrapper/gradle-wrapper.properties
=> [#377] Gradle update

android/src/main/java/com/github/mustafaozhan/ccc/android/app/CCCApplication.kt, config/build.gradle.kts, config/src/main/java/com/github/mustafaozhan/config/RemoteConfig.kt, config/src/main/java/com/github/mustafaozhan/config/model/AppConfig.kt, config/src/main/res/xml/default_remote_config.xml
=> [#383] RemoteConfig for ANRWatchDog

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/util/Extension.kt, config/src/main/java/com/github/mustafaozhan/config/model/AdConfig.kt, config/src/main/res/xml/default_remote_config.xml
=> [#385] RemoteConfig for banner ad

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt
=> [#387] isAdFree and currency_count bug

android/build.gradle.kts, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt, config/src/androidMain/kotlin/com/github/mustafaozhan/config/RemoteConfigImpl.kt, config/src/commonMain/kotlin/com/github/mustafaozhan/config/RemoteConfigImpl.kt, config/src/commonMain/kotlin/com/github/mustafaozhan/config/model/AdConfig.kt, config/src/iosMain/kotlin/com/github/mustafaozhan/config/RemoteConfig.kt, config/src/iosMain/kotlin/com/github/mustafaozhan/config/RemoteConfigImpl.kt, ios/CCC/UI/CalculatorView.swift, ios/CCC/UI/CurrenciesView.swift, settings.gradle.kts
=> [#393] using and mocking remoteConfig in client module

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#397] Fix failed test case

buildSrc/src/main/kotlin/Versions.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/util/Extension.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/ChangeBaseViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#366] Stubbing twice

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/SettingsRepositoryTest.kt
=> [#401] replace getters for test cases with invocation

config/src/androidMain/kotlin/com/github/mustafaozhan/config/RemoteConfigImpl.kt
=> [#403] RemoteConfig Crash fix

.github/workflows/main.yml
=> [#405] Skip previous job

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/main/MainActivity.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/util/Dialog.kt, client/build.gradle.kts, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainSEED.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt, config/src/androidMain/kotlin/com/github/mustafaozhan/config/RemoteConfigImpl.kt, config/src/commonMain/kotlin/com/github/mustafaozhan/config/model/AppConfig.kt, config/src/commonMain/kotlin/com/github/mustafaozhan/config/model/AppUpdate.kt
=> [#395] RemoteConfig for app update

.github/workflows/board.yml
=> [#410] Rename in Progress column

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt
=> [#408] fix codacy errors

android/src/main/java/com/github/mustafaozhan/ccc/android/util/Extension.kt, backend/src/jvmMain/kotlin/com/github/mustafaozhan/ccc/backend/controller/ApiController.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/settings/SettingsViewModel.kt, config/src/androidMain/kotlin/com/github/mustafaozhan/config/RemoteConfigImpl.kt
=> [#418] RemoteConfig get rid of Unnecessary logging

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/util/Extensions.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt
=> [#420] Last update date doesn't work offline mode fix

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/util/Extensions.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/extension/ExtensionsTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#422] Remove banner ad at first run

common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/settings/SettingsRepository.kt, common/src/commonMain/kotlin/com/github/mustafaozhan/ccc/common/settings/SettingsRepositoryImp.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/SettingsRepositoryTest.kt
=> [#425] Add session count

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainSEED.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, config/src/commonMain/kotlin/com/github/mustafaozhan/config/model/AdConfig.kt
=> [#415] RemoteConfig for Interstitial Ads

.github/workflows/main.yml, buildSrc/src/main/kotlin/Versions.kt
=> [#185] Codecov & Codacy merged reporting

gradle/wrapper/gradle-wrapper.properties
=> [#443] Gradle update

android/src/main/java/com/github/mustafaozhan/ccc/android/ui/main/MainActivity.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainViewModel.kt
=> [#438] Tidying events into lifeCycle events

android/build.gradle.kts, android/src/google/java/com/github/mustafaozhan/ccc/android/util/AppReviewUtil.kt, android/src/huawei/java/com/github/mustafaozhan/ccc/android/util/AppReviewUtil.kt, android/src/main/java/com/github/mustafaozhan/ccc/android/ui/main/MainActivity.kt
=> [#465] move AppReview in variant specific folders

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/helper/SessionManagerTest.kt
=> [#469] Failed Test fix

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/model/AppTheme.kt, client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/helper/SessionManagerTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#445] Inconsistent Coverage Results

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt
=> [#471] Add test case for MainViewModel onResume adjustSessionCount

client/src/commonMain/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt
=> [#473] Add test case for MainViewModel onResume checkAppUpdate

common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/CurrencyRepositoryTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/OfflineRatesRepositoryTest.kt
=> [#486] remove uncovered eq() implementation

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/helper/SessionManagerTest.kt
=> [#491] inconsistent coverage interstitialAdSessionCount

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/model/AppThemeTest.kt
=> [#496] Add missing test cases for AppTheme

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/util/Extension.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#497] remove getRandomDateLong

.github/workflows/board.yml
=> [#504] update project automation version

buildSrc/src/main/kotlin/Dependencies.kt, client/build.gradle.kts, common/build.gradle.kts
=> [#508] move to kotlin-test

client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/github/mustafaozhan/ccc/client/viewmodel/MainViewModelTest.kt, common/src/commonTest/kotlin/com/github/mustafaozhan/ccc/common/repo/ApiRepositoryTest.kt
=> [#482] remove uncovered any() implementation

ad/src/huawei/java/com/github/mustafaozhan/ad/Ads.kt, build.gradle.kts, common/src/jvmMain/kotlin/com/github/mustafaozhan/ccc/common/di/modules/JVMSettingsModule.kt
=> [#506] Configure Kotlin warnings as errors

README.md
=> [#524] Add README.md fake URL for testing

buildSrc/src/main/kotlin/config/BuildValues.kt, buildSrc/src/main/kotlin/config/Keys.kt
=> [#523] Fix error on fresh clone

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/Resources/Info.plist
=> [#537] set Bundle id for iOS

gradle/wrapper/gradle-wrapper.properties
=> [#543] Gradle update

client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/util/IOSCalculatorUtil.kt, gradle/wrapper/gradle-wrapper.properties, ios/CCC/UI/CalculatorView.swift
=> [#541] Fix 6 digit output crash

ios/CCC/UI/SettingsView.swift, ios/CCC/UI/SliderView.swift, ios/CCC/UI/SubView/SelectCurrencyView.swift
=> [#545] Fix iOS UI bugs

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt
=> [#556] update parsermob package name

android/src/main/kotlin/com/oztechan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/adremove/RemoveAdsAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/changebase/ChangeBaseAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/changebase/ChangeBaseBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/main/MainActivity.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/slider/SliderFragment.kt
=> [#558] update basemob package name 

android/src/main/kotlin/com/oztechan/ccc/android/ui/slider/SliderFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/slider/SliderPagerAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/Dialog.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt, billing/src/google/kotlin/com/oztechan/ccc/billing/BillingManagerImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/helper/SessionManagerImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/RemoveAdType.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt
=> [#561] update scopemob package name

android/src/main/kotlin/com/oztechan/ccc/android/Application.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/ApiController.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/ChangeBaseViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/Logger.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/repo/ApiRepositoryTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/repo/CurrencyRepositoryTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/repo/OfflineRatesRepositoryTest.kt, config/src/androidMain/kotlin/com/oztechan/ccc/config/ConfigManagerImpl.kt
=> [#562] update logmob package name

android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorAdapter.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, ios/CCC/UI/CalculatorView.swift
=> [#568] Move show conversion long click listener to currency flag

.github/workflows/testing.yml
=> [#574] Publish Huawei variant via Firebase App Distrubution

.github/workflows/testing.yml
=> [#576] Add missing Huawei job into app distribution

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#586] convert versionName to 0.0.XXX for test builds

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#588] Auto set version and build number iOS

analytics/build.gradle.kts, analytics/src/main/kotlin/com/oztechan/ccc/analytics/AnalyticsManagerImpl.kt, analytics/src/main/kotlin/com/oztechan/ccc/analytics/model/UserProperty.kt, analytics/src/main/kotlin/com/oztechan/ccc/analytics/util/AnalyticsUtil.kt, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt
=> [#578] remove gsm hsm tracking

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#592] fix agvtools fails on non-mac enviroment

android/build.gradle.kts, backend/build.gradle.kts, buildSrc/src/main/kotlin/ProjectSettings.kt, client/build.gradle.kts, common/build.gradle.kts
=> [#583] Update group and project IDs

billing/src/google/kotlin/com/oztechan/ccc/billing/BillingManagerImpl.kt
=> [#594] RemoveAds screen doesn't load second time

android/src/main/res/layout/fragment_slider.xml, android/src/main/res/values/dimens.xml, android/src/main/res/values/styles.xml
=> [#596] fix slider bottom dots layout

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#604] Fix local versioning error

.gitignore, .gitmodules, README.md, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, client/build.gradle.kts, settings.gradle.kts
=> [#610] Replace parsermob submodule to library

.github/workflows/testing.yml
=> [#627] Fix App Distribution

ios/fastlane/Fastfile
=> [#631] add test device

.github/workflows/testing.yml, ios/fastlane/Fastfile
=> [#634] Cleaner lanes for iOS

ios/CCC.xcodeproj/project.pbxproj, ios/Gemfile.lock, ios/Podfile.lock, ios/fastlane/Fastfile
=> [#636] Dynamic fastlane builds and auto signing

.github/workflows/release.yml, ios/fastlane/Fastfile
=> [#638] Release automation for iOS

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, android/.gitignore
=> [#648] Update gitignore and add agconnect keys

ios/CCC/UI/MainView.swift, ios/CCC/UI/SliderView.swift
=> [#653] Temporary disable Slider intro for iOS

ios/CCC/UI/MainView.swift, ios/CCC/UI/SliderView.swift
=> [#615] Navigation bug fix

ios/CCC/UI/CalculatorView.swift, ios/CCC/UI/ChangeBaseView.swift, ios/CCC/UI/CurrenciesView.swift, ios/CCC/UI/MainView.swift, ios/CCC/UI/SettingsView.swift
=> [#656] Add better logging in SwiftUI effects

ios/CCC/UI/CalculatorView.swift
=> [#658] iOS duplicated row fix

.github/workflows/dependencies.yml
=> [#640] Add dependencies report artifact, schedule task for Saturday morning

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/UI/Calculator/CalculatorItemView.swift, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Calculator/InputView.swift, ios/CCC/UI/Calculator/KeyboardView.swift, ios/CCC/UI/Calculator/OutputView.swift, ios/CCC/UI/Calculator/RateStateView.swift
=> [#660] package CalculatorView

ios/CCC/UI/Calculator/InputView.swift, ios/CCC/UI/Calculator/OutputView.swift, ios/CCC/UI/Calculator/RateStateView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/Main/MainView.swift
=> [#585] Update iOS animations

.github/workflows/release.yml
=> [#646] UploadHuaweiAppGallery

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#539] Huawei versioning fix

.github/workflows/dependency.yml
=> [#689] Fix Dependency CI task

android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/selectcurrency/SelectCurrencyAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt, ios/CCC/Util/Extensions.swift, resources/src/androidMain/kotlin/com/oztechan/ccc/resources/AndroidResources.kt, resources/src/commonMain/kotlin/com/oztechan/ccc/resources/Resources.kt, resources/src/iosMain/kotlin/com/oztechan/ccc/resources/IOSResources.kt
=> [#683] move Resource utils into resources module

buildSrc/src/main/kotlin/Versions.kt, gradle/wrapper/gradle-wrapper.properties
=> [#694] Gradle update

buildSrc/src/main/kotlin/Versions.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/entity/CurrencyResponseEntity.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/entity/RatesEntity.kt, common/src/jvmMain/kotlin/com/oztechan/ccc/common/di/modules/JVMSettingsModule.kt
=> [#712] Kotlin Update

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, android/build.gradle.kts
=> [#705] ad applicationId and versionName suffix to debug builds

android/src/main/kotlin/com/oztechan/ccc/android/ui/main/MainActivity.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/DeviceUtil.kt, resources/src/commonMain/resources/MR/base/strings.xml
=> [#676] add huawei link to Support Us logic

buildSrc/src/main/kotlin/Versions.kt
=> [#719] Library updates

ios/CCC/UI/Currencies/SelectionView.swift, ios/CCC/UI/Settings/SettingsView.swift
=> [#677] Remove bottom safe areas for Currencies and Settings

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notifications/NotificationsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notifications/NotificationsViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, ios/CCC.xcodeproj/project.pbxproj, ios/CCC/DI/Koin.swift, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Notifications/NotificationCurrencyItem.swift, ios/CCC/UI/Notifications/NotificationStateView.swift, ios/CCC/UI/Notifications/NotificationsToolbarView.swift, ios/CCC/UI/Notifications/NotificationsView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/Settings/SettingsView.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#716] Add back Notification Screen

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notification/NotificationSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notification/NotificationViewModel.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/db/notification/NotificationRepository.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/db/notification/NotificationRepositoryImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/db/sql/Notification.sq, ios/CCC/UI/Notifications/NotificationItem.swift, ios/CCC/UI/Notifications/NotificationView.swift
=> [#723] Add Relation and Rate change capability to notifications

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, ios/CCC/UI/Notifications/NotificationItem.swift, ios/CCC/UI/Settings/SettingsView.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#725] Show active notifications

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/UI/Calculator/CalculatorItemView.swift, ios/CCC/UI/Calculator/OutputView.swift, ios/CCC/UI/Currencies/CurrenciesItemView.swift, ios/CCC/UI/Notifications/NotificationItem.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyItemView.swift, ios/CCC/UI/SubView/CurrencyImageView.swift
=> [#727] Create CurrencyImageView

android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notification/NotificationSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notification/NotificationViewModel.kt, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Notifications/NotificationItem.swift, ios/CCC/UI/Notifications/NotificationView.swift, ios/CCC/Util/SnackBar.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#734] Handle maximum input error in Notifications

client/src/commonMain/kotlin/com/oztechan/ccc/client/mapper/Notification.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/Notification.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notification/NotificationSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/notification/NotificationViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, ios/CCC/UI/Notifications/NotificationItem.swift, ios/CCC/UI/Notifications/NotificationView.swift, ios/CCC/Util/SnackBar.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#736] Handle input validation in Notifications

client/src/androidMain/kotlin/com/oztechan/ccc/client/util/AndroidCalculatorUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/mapper/Notification.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/util/IOSCalculatorUtil.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/db/notification/NotificationRepositoryImpl.kt, ios/CCC/UI/Notifications/NotificationItem.swift
=> [#740] Style Notification Rate Input field

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/UI/Watchers/WatchersView.swift, ios/CCC/Util/NotificationManager.swift
=> [#756] Create NotificationManager

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/UI/Watchers/WatchersView.swift, ios/CCC/Util/NotificationManager.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#758] Reflect Notification Permission change and link to Settings

ios/CCC/Util/NotificationManager.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#760] Add send Notification capability

.github/workflows/dependency.yml
=> [#762] Fix Project Health task

client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/session/SessionManager.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/session/SessionManagerImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/manager/SessionManagerTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#766] Convert Helpers to Managers

buildSrc/src/main/kotlin/Versions.kt
=> [#769] Kotlin update

ios/CCC/UI/Watchers/WatchersView.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#777] Change exact time definition in Watchers

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt
=> [#779] Selecting base currency on fly doesn't work at first start

client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CoroutineUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/base/BaseViewModel.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/util/IOSCoroutineUtil.kt, ios/CCC/Util/ObservableSEED.swift
=> [#782] Move observe utility into common and move sqldelight closable

ios/CCC/Util/NotificationManager.swift
=> [#778] Notification permission issue in iOS 15.5

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
=> [#787] Unify conversion calculation

client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/background/BackgroundManager.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/background/BackgroundManagerImpl.kt, ios/CCC/Application.swift, ios/CCC/DI/Koin.swift
=> [#784] BackgroundManager Implementation

ios/CCC/UI/Watchers/WatchersToolbarView.swift, ios/CCC/UI/Watchers/WatchersView.swift
=> [#789] Update Watcher headline style

ios/CCC/UI/Watchers/WatchersToolbarView.swift, ios/CCC/UI/Watchers/WatchersView.swift, resources/src/commonMain/resources/MR/base/strings.xml
=> [#791] Click Add button warning

ios/CCC/Application.swift, ios/CCC/Resources/Info.plist
=> [#795] Create BackgroundTask for Watcher

ios/CCC/Application.swift, ios/CCC/Resources/Info.plist, ios/CCC/Util/NotificationManager.swift
=> [#796] Create alert to handle Watchers when the app is open

client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/di/KoinIOS.kt, ios/CCC/DI/Koin.swift
=> [#799] Inject Swift protocols by koin

buildSrc/src/main/kotlin/ProjectSettings.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/background/BackgroundManagerImpl.kt, ios/CCC/Application.swift, ios/CCC/Util/NotificationManager.swift
=> [#801] Increase version and release adjustments

client/src/androidMain/kotlin/com/oztechan/ccc/client/base/BaseViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/base/BaseViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/base/BaseViewModel.kt
=> [#805] Rename clientScope to viewModelScope

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, client/build.gradle.kts, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/Extension.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/BaseViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/build.gradle.kts, common/src/androidMain/kotlin/com/oztechan/ccc/common/Actual.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/Expect.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/CurrencyTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/repo/ApiRepositoryTest.kt, common/src/iosMain/kotlin/com/oztechan/ccc/common/Actual.kt, common/src/jvmMain/kotlin/com/oztechan/ccc/common/Actual.kt, gradle.properties
=> [#447] Move New Coroutines Memory management Model

android/src/main/kotlin/com/oztechan/ccc/android/di/PlatformModule.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/di/modules/ControllerModule.kt, buildSrc/src/main/kotlin/Versions.kt, client/src/androidMain/kotlin/com/oztechan/ccc/client/di/module/AndroidModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/ApiModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DatabaseModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/SettingsModule.kt
=> [#773] Update koin

android/src/main/kotlin/com/oztechan/ccc/android/ui/main/MainActivity.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt, buildSrc/src/main/kotlin/Versions.kt
=> [#692] Update navigation Library

android/src/main/kotlin/com/oztechan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/SnackBar.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt
=> [#814] Make showSnack extension of the view

ios/.gitignore, ios/CCC.xcodeproj/project.pbxproj, ios/Podfile.lock, ios/podfile
=> [#817] Move NavigationStack to Swift Package Manager

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/CurrencyRoute.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/di/KoinIOS.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/Koin.kt, ios/CCC/DI/Koin.swift, ios/Podfile.lock
=> [#831] replace getDependency with inject

common/src/commonMain/kotlin/com/oztechan/ccc/common/api/model/CurrencyResponse.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/model/Rates.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/service/ApiService.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/service/ApiServiceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/mapper/CurrencyResponse.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/mapper/OfflineRates.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/mapper/Rates.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/CurrencyResponseTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/OfflineRatesTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/RatesTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/repo/ApiRepositoryTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/repo/OfflineRatesRepositoryTest.kt
=> [#835] split model and uimodel

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/ApiController.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/di/modules/ControllerModule.kt, client/src/androidMain/kotlin/com/oztechan/ccc/client/di/KoinAndroid.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/di/KoinIOS.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/free/FreeApi.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/free/FreeApiImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/model/CurrencyResponse.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/model/Rates.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/repo/ApiRepository.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/repo/ApiRepositoryImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/service/ApiService.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/api/service/ApiServiceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/ApiModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/ServiceModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/service/free/FreeApiService.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/service/free/FreeApiServiceImpl.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/repo/ApiRepositoryTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BaseServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/FreeApiServiceTest.kt
=> [#837] Create Free API and Service

common/src/commonMain/kotlin/com/oztechan/ccc/common/service/BaseNetworkService.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/service/backend/BackendApiServiceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/service/free/FreeApiServiceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/service/premium/PremiumApiServiceImpl.kt
=> [#843] Create BaseNetworkService

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, client/src/androidMain/kotlin/com/oztechan/ccc/client/di/KoinAndroid.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/session/SessionManagerImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/manager/SessionManagerTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/di/KoinIOS.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/settings/SettingsDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/settings/SettingsDataSourceImp.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DataSourceModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/SettingsModule.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/SettingsDataSourceTest.kt
=> [#845] Create SettingsDataSource and DataSourceModule

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DataSourceModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DatabaseModule.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/CurrencyRepositoryTest.kt
=> [#847] convert CurrencyRepository to CurrencyDataSource

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/ApiController.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/RootingController.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/offlinerates/OfflineRatesDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/offlinerates/OfflineRatesDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DataSourceModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DatabaseModule.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/CurrencyDataSourceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/OfflineRatesDataSourceTest.kt
=> [#848] convert OfflineRatesRepository to OfflineRatesDataSource

client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/background/BackgroundManagerImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DataSourceModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/DatabaseModule.kt
=> [#851] convert WatcherRepository to WatcherDataSource

common/src/commonMain/kotlin/com/oztechan/ccc/common/error/BaseNetworkException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/EmptyParameterException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/ModelMappingException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/NetworkException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/TimeoutException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/UnknownNetworkException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/model/EmptyParameterException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/service/BaseNetworkService.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BackendApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/FreeApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/PremiumApiServiceTest.kt
=> [#853] Create local errors and error mapping

client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/session/SessionManagerImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/manager/SessionManagerTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, config/src/androidMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/ConfigService.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt, config/src/iosMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt
=> [#855] Convert ConfigManager to ConfigService

client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/manager/background/BackgroundManager.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/background/BackgroundRepository.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/background/BackgroundRepositoryImpl.kt, ios/CCC/Application.swift
=> [#857] Create BackgroundManager to BackgroundRepository

client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/session/SessionRepository.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/session/SessionRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/SessionRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#859] Convert SessionManager to SessionRepository

client/build.gradle.kts, common/build.gradle.kts, config/build.gradle.kts, res/build.gradle.kts
=> [#731] iOS platform dependencies update for KMP modules

android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt
=> [#864] Backstackentry bug

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, ios/CCC/UI/SubView/BannerAdView.swift, ios/Podfile.lock
=> [#867] Update pods and fix errors

ios/CCC.xcodeproj/project.pbxproj, ios/Podfile.lock, ios/podfile
=> [#821] Move AdMob to SPM

android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt, res/build.gradle.kts, res/src/androidMain/AndroidManifest.xml, res/src/commonMain/kotlin/com/oztechan/ccc/res/Resources.kt, res/src/iosMain/kotlin/com/oztechan/ccc/res/IOSResources.kt
=> [#875] rename missed res packages

client/src/iosMain/kotlin/com/oztechan/ccc/client/Logger.kt, ios/CCC.xcodeproj/project.pbxproj, ios/CCC/Application.swift, ios/Podfile.lock
=> [#876] fix or remove debug version of crashlytics data collection

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, ios/CCC.xcodeproj/project.pbxproj, ios/CCC.xcworkspace/contents.xcworkspacedata, ios/Podfile.lock, ios/podfile, res/.gitignore, res/build.gradle.kts
=> [#825] move Res to embedAndSignAppleFrameworkForXcode

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, client/.gitignore, client/build.gradle.kts, ios/CCC.xcodeproj/project.pbxproj, ios/Podfile.lock, ios/podfile
=> [#880] move Client to embedAndSignAppleFrameworkForXcode

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, ios/.gitignore, ios/CCC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [#885] add workspace and project files into git

ios/CCC.xcodeproj/project.pbxproj
=> [#889] iOS crash reporting problem

ios/fastlane/Fastfile
=> [#887] Reorganise fastlane methods

buildSrc/src/main/kotlin/Versions.kt, gradle/wrapper/gradle-wrapper.properties
=> [#891] Dependency Updates

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, client/.gitignore, client/build.gradle.kts, ios/CCC.xcodeproj/project.pbxproj, ios/Podfile.lock, ios/podfile
This reverts commit 050c8dd.## Description
Resolves #894
=> [#894] Move client to cocoapods

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, ios/CCC.xcodeproj/project.pbxproj, ios/CCC.xcworkspace/contents.xcworkspacedata, ios/Podfile.lock, ios/podfile, res/.gitignore, res/build.gradle.kts
This reverts commit 050c8dd.## Description
Resolves #895
=> [#895] Move res to cocoapods

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, ios/CCC.xcodeproj/project.pbxproj, ios/CCC/Application.swift, ios/fastlane/Fastfile
=> [#901] Fix Firebase issue

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#903] Fix initial run issues

README.md
=> [#884] Update iOS instructions

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/Application.swift, ios/CCC/Util/EnvironmentUtil.swift
=> [#909] Create Environment Util for iOS

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, ios/CCC.xcodeproj/project.pbxproj
=> [#912] move GoogleService-info.plist into Resources

ios/CCC/Util/EnvironmentUtil.swift
=> [#914] Fix EnvironmentUtil bug

common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/BaseDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/DatabaseException.kt
=> [#916] Create BaseDataSource

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, README.md, analytics/.gitignore, analytics/build.gradle.kts, android/build.gradle.kts, client/build.gradle.kts, client/src/iosMain/kotlin/com/oztechan/ccc/client/di/IOSKoin.kt, ios/CCC.xcodeproj/project.pbxproj, ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/CCC/Analytics/AnalyticsManagerImpl.swift, ios/CCC/DI/Koin.swift, ios/Podfile.lock, ios/podfile
=> [#925] iOS analaytics integration

analytics/src/androidMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManagerImpl.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManager.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/Event.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/selectcurrency/SelectCurrencyBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/submodules/ViewModelModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, ios/CCC/Analytics/AnalyticsManagerImpl.swift
=> [#927] Move event tracking to Multiplatform

analytics/src/androidMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManagerImpl.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManager.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/ScreenName.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/selectcurrency/SelectCurrencyBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/slider/SliderFragment.kt, ios/CCC/Analytics/AnalyticsManagerImpl.swift, ios/CCC/Resources/Info.plist, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/UI/Slider/SliderView.swift, ios/CCC/UI/Watchers/WatchersView.swift
=> [#929] Unify and implement screen tracking for both platforms

analytics/src/androidMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManagerImpl.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManager.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/Event.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/EventParam.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/Param.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, ios/CCC/Analytics/AnalyticsManagerImpl.swift
=> [#931] Redesign event tracking and params

README.md
=> [#906] Update Testing information

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, ios/.gitignore, ios/CCC.xcodeproj/project.pbxproj, ios/CCC.xcodeproj/xcshareddata/xcschemes/CCC.xcscheme, ios/CCC/Resources/Debug/Config.xcconfig, ios/CCC/Resources/Debug/GoogleService-Info.plist
Resolves #934
it can fix the #626
=> [#934] iOS better dealing with secret files

analytics/src/androidMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManagerImpl.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/AnalyticsManager.kt, analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/UserProperty.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/main/MainActivity.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/DeviceUtil.kt, client/src/androidMain/kotlin/com/oztechan/ccc/client/Device.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/submodules/ViewModelModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/AppTheme.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/Device.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, ios/CCC/Analytics/AnalyticsManagerImpl.swift
=> [#247] Move UserProperty tracking to Multiplatform

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/BaseDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/submodules/DataSourceModule.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/CurrencyDataSourceTest.kt
=> [#918] Move CurrencyDataSource to new BaseDataSource

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/RootingController.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/offlinerates/OfflineRatesDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/offlinerates/OfflineRatesDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/submodules/DataSourceModule.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/OfflineRatesDataSourceTest.kt
=> [#920] Move OfflineRateDataSource to new BaseDataSource

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/BaseDBDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/offlinerates/OfflineRatesDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/modules/submodules/DataSourceModule.kt
=> [#922] Move WatcherDataSource to new BaseDataSource

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/Application.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/Util/Alert.swift
=> [#937] Add SwiftMessages Alert

ios/CCC/Application.swift, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/Main/MainView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/Util/Alert.swift
=> [#936] Enable Ads in iOS

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt
=> [#942] Start-up crash due to early used device property

README.md
=> [#944] Update mermaid diagram

client/src/commonMain/kotlin/com/oztechan/ccc/client/model/AppTheme.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [#946] Add test cases for MainViewModel user properties

android/google-services.json
=> [#959] Android app doesn't build in develop branch

client/src/commonMain/kotlin/com/oztechan/ccc/client/model/AppTheme.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/model/AppThemeTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt
=> [#947] Add test case for getAnalyticsThemeName

client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/SessionRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt
=> [#956] Some tests fails due to epoch milliseconds

ios/CCC/UI/Slider/SliderView.swift
=> [#952] Enable Disable Ads Slider for iOS

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/session/SessionRepository.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/session/SessionRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, ios/CCC/UI/Settings/SettingsView.swift
=> [#965] Do not show RemoveAds until Ads are shown

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
=> [#961] BaseChange event occurs twice

android/src/main/kotlin/com/oztechan/ccc/android/ui/main/MainActivity.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/DeviceUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/Device.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, res/src/commonMain/resources/MR/base/strings.xml
=> [#966] Move market links into device

ios/CCC/Application.swift, ios/CCC/DI/Koin.swift
=> [#963] Simplify iOS Koin logic

android/src/main/kotlin/com/oztechan/ccc/android/Application.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/Logger.kt, ios/CCC/Application.swift, ios/Podfile.lock
=> [#207] Ensure Crashlytics initialisation at first

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt
=> [#976] Support different decimals for Watcher

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, ios/CCC/UI/Watchers/WatchersView.swift
=> [#978] Add padding to watchers if there is no Ad

android/src/main/kotlin/com/oztechan/ccc/android/util/SnackBar.kt
=> [#980] Fix SnackBar

.github/workflows/main.yml, build.gradle.kts, buildSrc/src/main/kotlin/Versions.kt
=> [#988] Update Kover

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BackendApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/FreeApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/PremiumApiServiceTest.kt
=> [#510] use assertIs

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#991] State null check asserts

android/build.gradle.kts
=> [#995] Disable Firebase performance for debug mode

.github/workflows/board.yml, .github/workflows/dependency.yml, .github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml
=> [#997] Update GitHub Actions and use gradle-build-action

android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorAdapter.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/mapper/Currency.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/Currency.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/mapper/CurrencyTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, ios/CCC/UI/Calculator/CalculatorItemView.swift
=> [#983] Convert rate of Currency printed on Screen to String

ad/src/google/kotlin/com/oztechan/ccc/ad/AdManagerImpl.kt, ad/src/huawei/kotlin/com/oztechan/ccc/ad/AdManagerImpl.kt, ad/src/main/kotlin/com/oztechan/ccc/ad/AdManager.kt, ad/src/main/kotlin/com/oztechan/ccc/ad/BannerAdView.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt
=> [#1003] Destroy Banners when fragment is being destroyed in order to prevent leaks

android/src/main/AndroidManifest.xml
=> [#1004] Optimize MobileAds SDK initialisation and Ad load

client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/settings/SettingsDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/settings/SettingsDataSourceImp.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/SettingsDataSourceTest.kt
=> [#982] Save and use precision from local

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
=> [#1010] Revert Multiple base change bug changes and track only once

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt
=> [#950] Add missing UserProperty test cases

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#1002] Add test cases for precision

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [#1019] Add test cases for failed api and successful db result

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [#1021] Add test cases for failed api and failed db result

client/src/commonTest/kotlin/com/oztechan/ccc/client/model/AppThemeTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/model/RemoveAdTypeTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/CurrencyTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/LongTest.kt
=> [#993] Using precise assert methods

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [#1013] Add test cases for onKeyPress

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt
=> [#1023] Add missing test cases for isActive of a currency

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt
=> [#1027] Add WatchersViewModelTest cases

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [#1017] Add test cases for onItemClick

android/src/main/kotlin/com/oztechan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/main/MainActivity.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/Dialog.kt
=> [#1015] Make dialogs extension of activity

android/src/main/AndroidManifest.xml
=> [#1039] Add advertising ID for Android 13

ad/build.gradle.kts, ad/src/main/AndroidManifest.xml, android/build.gradle.kts, android/src/main/AndroidManifest.xml
=> [#1041] Move Ad related build configurations into ad module

analytics/src/androidMain/AndroidManifest.xml, android/src/main/AndroidManifest.xml
=> [#1043] Move analytics related configurations into analytics module

android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#1037] Android 13 Support

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/AppTheme.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/model/AppThemeTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#1033] Remove order from AppTheme and use ordinals

common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/WatcherDataSourceTest.kt
=> [#1035] Add test cases for WatcherDataSource

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt
=> [#1031] add test cases for WatchersViewModel onRateChange

res/build.gradle.kts, res/src/commonTest/kotlin/com/oztechan/ccc/res/ResourcesTest.kt
=> [#1051] Add res test cases

analytics/build.gradle.kts, analytics/src/commonTest/kotlin/com/oztechan/ccc/analytics/model/EventTest.kt, analytics/src/commonTest/kotlin/com/oztechan/ccc/analytics/model/ScreenNameTest.kt
=> [#1049] Add analytics test cases

android/build.gradle.kts, android/src/test/kotlin/com/oztechan/ccc/android/util/PurchaseUtilTest.kt, buildSrc/src/main/kotlin/Dependencies.kt
=> [#1053] Add android test cases

analytics/src/commonTest/kotlin/com/oztechan/ccc/analytics/model/EventTest.kt, analytics/src/commonTest/kotlin/com/oztechan/ccc/analytics/model/ScreenNameTest.kt, android/src/test/kotlin/com/oztechan/ccc/android/util/PurchaseUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/mapper/CurrencyResponseTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/mapper/CurrencyTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/mapper/WatcherTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/model/AppThemeTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/model/RemoveAdTypeTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/DateUtilTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/BooleanTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/CurrencyResponseTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/CurrencyTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/LongTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/OfflineRatesTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/RatesTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/WatcherTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/util/DateUtilTest.kt, res/src/commonTest/kotlin/com/oztechan/ccc/res/ResourcesTest.kt, test/src/commonMain/kotlin/com/oztechan/ccc/test/BaseTest.kt
=> [#1057] Create BaseTest

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt, test/src/commonMain/kotlin/com/oztechan/ccc/test/BaseTest.kt, test/src/commonMain/kotlin/com/oztechan/ccc/test/BaseViewModelTest.kt
=> [#1061] Create BaseViewModelTest

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/CurrencyDataSourceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/OfflineRatesDataSourceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/SettingsDataSourceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/WatcherDataSourceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/CurrencyResponseTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/OfflineRatesTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/mapper/RatesTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BackendApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/FreeApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/PremiumApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/util/TestUtil.kt, test/src/commonMain/kotlin/com/oztechan/ccc/test/util/TestUtil.kt
=> [#1062] Create TestUtil

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/repository/api/ApiRepositoryImpl.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/util/ApiUtil.kt
=> [#1071] Create ApiUtil

backend/build.gradle.kts, backend/src/jvmTest/kotlin/com/oztechan/ccc/backend/util/ApiUtilTest.kt
=> [#1073] Add backend test dependency and Create ApiUtilTest

ios/CCC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/UI/Slider/SliderView.swift, ios/CCC/UI/Watchers/WatchersView.swift, ios/Podfile.lock
=> [#1065] Xcode 14 update

gradle.properties
=> [#1046] Remove unnecessary gradle properties

ios/CCC/UI/SubView/BannerAdView.swift
=> [#1077] BannerAd crash in iOS 16

common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/WatcherDataSourceTest.kt
=> [#1093] Add missing WatcherDataSource test cases

common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/OfflineRatesDataSourceTest.kt
=> [#1091] Add missing OfflineRatesDataSource test cases

common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/CurrencyDataSourceTest.kt
=> [#1087] Add missing CurrencyDataSource test cases

common/src/commonMain/kotlin/com/oztechan/ccc/common/error/BaseNetworkException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/EmptyParameterException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/ModelMappingException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/NetworkException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/TerminationException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/TimeoutException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/error/UnknownNetworkException.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/service/BaseNetworkService.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BackendApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BaseNetworkServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/FreeApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/PremiumApiServiceTest.kt
=> [#1080] Test for Service error mapping

common/src/commonMain/kotlin/com/oztechan/ccc/common/error/DatabaseException.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/BaseDataSourceTest.kt
=> [#1085] Test for DataSource error mapping

android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Watchers/WatchersView.swift, res/src/commonMain/resources/MR/base/strings.xml
=> [#1095] Replace MaximumInput with TooBigNumber

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [#1097] Add TooBigInput test case

client/build.gradle.kts, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepository.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt
=> [#1100] Add Versioning into client

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt
=> [#1109] Add verifyCurrentBase test case when it is empty

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/res/drawable/ic_version.xml, android/src/main/res/layout/fragment_settings.xml, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, res/src/commonMain/resources/MR/base/strings.xml
=> [#1099] Add Version row for Android

gradlew, gradlew.bat
=> [#1113] Update gradlew and gradlew.bat with latest KMP example

android/src/main/kotlin/com/oztechan/ccc/android/ui/selectcurrency/SelectCurrencyBottomSheet.kt, android/src/main/res/layout/bottom_sheet_select_currency.xml, android/src/main/res/values/styles.xml, res/src/commonMain/resources/MR/base/strings.xml
=> [#1120] Add link to Currencies in Select Currency for Android

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt
=> [#1117] Add missing update state test cases

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [#1115] Add calculateOutput finite output test cases

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt
=> [#1111] Add verifyCurrentBase test case when currentBase is unset

android/src/main/kotlin/com/oztechan/ccc/android/ui/main/MainActivity.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/DeviceUtil.kt, android/src/test/kotlin/com/oztechan/ccc/android/util/DeviceUtilTest.kt
=> [#1134] Add DeviceUtil test

client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CoroutineUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencySEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt, config/build.gradle.kts
=> [#1132] Make use of new coroutines update method

client/src/iosMain/kotlin/com/oztechan/ccc/client/Logger.kt, ios/CCC/Application.swift
=> [#1125] Add extra logs for iOS crashes

android/src/main/res/values/dimens.xml, android/src/main/res/values/styles.xml
=> [#1105] Make settings items smaller for Android

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt
=> [#1144] Improve AdRemoveViewModel tests

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#1142] Improve SettingsViewModel tests

ios/CCC/UI/Settings/SettingsView.swift
=> [#1103] add Version row for iOS

ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift
=> [#1119] Add link to Currencies in Select Currency for iOS

ios/CCC/UI/Main/MainView.swift
=> [#1130] Change screen transitionType until iOS16 bug is fixed

README.md
=> [#1136] Add architectural diagram to README.md

ios/CCC/Util/InterstitialAd.swift
=> [#1138] InterstitialAd crash fix

client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt
=> [#1146] Increase AdRemoveViewModel coverage

.github/workflows/dependency.yml, .github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, README.md
=> [#1149] Add submodules setup

.github/workflows/dependency.yml, .github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, .gitignore, .gitmodules, README.md, ad/build.gradle.kts, android/build.gradle.kts, backend/build.gradle.kts, billing/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, client/build.gradle.kts, common/build.gradle.kts, config/build.gradle.kts, settings.gradle.kts, test/build.gradle.kts
=> [#1150] Add LogMob as log module

buildSrc/src/main/kotlin/Versions.kt, res/build.gradle.kts
=> [#1088] Update Android Gradle Plugin

.gitignore, .gitmodules, README.md, android/build.gradle.kts, billing/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, client/build.gradle.kts, settings.gradle.kts
=> [#1153] Add ScopeMob as scope module

.gitignore, .gitmodules, README.md, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt, client/build.gradle.kts, settings.gradle.kts
=> [#1159] add ParserMob as parser module

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt
=> [#1148] Update Dependencies

.github/workflows/main.yml, android/google-services.json
=> [#1167] Add fake services.json for both debug and release

README.md, android/build.gradle.kts
=> [#1162] Update test module dependencies in README.md

client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt
=> [#1178] Delete empty line in version

client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/BackgroundRepositoryTest.kt
=> [#1173] Add BackgroundRepository tests

buildSrc/src/main/kotlin/Versions.kt
=> [#810] Update desugaring library

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [#1175] Update version to 2.8.0

client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AdRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, config/src/androidMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AdConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AppConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AppReview.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AppUpdate.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/AdConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/AppConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/AppReview.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/mapper/AppUpdate.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/model/AdConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/model/AppConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/model/AppReview.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/model/AppUpdate.kt, config/src/iosMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt
=> [#1184] Mapping and adding entity/models into config module

README.md, config/build.gradle.kts, config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/AdConfigTest.kt, config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/AppConfigTest.kt, config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/AppReviewTest.kt, config/src/commonTest/kotlin/com/oztechan/ccc/config/mapper/AppUpdateTest.kt
=> [#1188] Add mapper tests into config module

config/build.gradle.kts
=> [#1194] Remove cocoapods from config

ad/build.gradle.kts, ad/src/google/kotlin/com/oztechan/ccc/ad/AdManagerImpl.kt, ad/src/huawei/kotlin/com/oztechan/ccc/ad/AdManagerImpl.kt, ad/src/main/kotlin/com/oztechan/ccc/ad/di/AdModule.kt, android/src/main/kotlin/com/oztechan/ccc/android/Application.kt, android/src/main/kotlin/com/oztechan/ccc/android/di/module/AppModule.kt, client/src/androidMain/kotlin/com/oztechan/ccc/client/di/AndroidKoin.kt
=> [#1190] Create DI module for ad

android/src/main/kotlin/com/oztechan/ccc/android/Application.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/IOSLogger.kt, ios/CCC/Application.swift, ios/Podfile.lock, test/src/commonMain/kotlin/com/oztechan/ccc/test/BaseTest.kt
=> [1182] Reorganise logging and add kermit transitive

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml, README.md, android/build.gradle.kts, client/build.gradle.kts, ios/CCC/Analytics/AnalyticsManagerImpl.swift, ios/CCC/Application.swift, ios/CCC/DI/Koin.swift, ios/CCC/UI/Calculator/CalculatorItemView.swift, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesItemView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/Main/MainView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyItemView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/UI/Slider/SliderView.swift, ios/CCC/UI/Watchers/WatcherItem.swift, ios/CCC/UI/Watchers/WatchersView.swift, ios/CCC/Util/Extensions.swift, ios/CCC/Util/NotificationManager.swift, ios/CCC/Util/ObservableSEED.swift, ios/Podfile.lock, ios/podfile, provider/build.gradle.kts, provider/src/iosMain/kotlin/com/oztechan/ccc/injector/IOSKoin.kt, provider/src/iosMain/kotlin/com/oztechan/ccc/injector/IOSLogger.kt
=> [#1202] Replace provider with client

README.md
=> [#1210] Update Readme.MD with provider module

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/Main/MainView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/UI/Watchers/WatchersView.swift, ios/CCC/Util/ObservableSEEDViewModel.swift
=> [#1200] Move Koin injection into ObservableSEEDViewModel

analytics/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/ProjectSettings.kt, config/build.gradle.kts, provider/build.gradle.kts, res/build.gradle.kts
=> [#1216] Unify Pods and its attributes

docs/CONTRIBUTING.md, docs/ISSUE_TEMPLATE.md, docs/PULL_REQUEST_TEMPLATE.md
=> [#1224] Update templates for new project management rules

client/src/commonMain/kotlin/com/oztechan/ccc/client/base/BaseSEEDViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/Main/MainView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/UI/Watchers/WatchersView.swift, ios/CCC/Util/ObservableSEEDViewModel.swift
=> [#1212] Use generics for SEEDViewModel

android/src/main/kotlin/com/oztechan/ccc/android/Application.kt
=> [#1198] Remove ANRWatchDog for Android 11+

ios/CCC/UI/Main/MainView.swift
=> [#1220] make sliding avaliable less than iOS 16

settings.gradle.kts
=> [#1218] reorganize settings.gradle

ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/CCC/Application.swift, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/UI/Watchers/WatchersView.swift, ios/CCC/Util/Extensions.swift, ios/fastlane/Fastfile
=> [#1123] iOS 16 list background issue

gradle.properties
=> [#1222] remove native memorry model gradle property

.github/dependabot.yml
=> [#1236] Dependabot PR titles and environment variables

.github/dependabot.yml
=> [#1239] Automatic Dependency updates with Dependabot

.github/workflows/dependency.yml, build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt
=> [#1241] Remove Build Health

buildSrc/src/main/kotlin/Versions.kt
=> [#1244] Update Crashlytics

.github/workflows/dependency.yml
=> [#1235] Set Job output for dependency updates

.github/workflows/dependency.yml, .github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml
=> [#1256] rename Slack channel ccc to ccc-github

buildSrc/src/main/kotlin/Versions.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/ad/AdRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AdRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/module/CommonModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/module/submodule/DataSourceModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/module/submodule/StorageModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/storage/AppStorage.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/storage/AppStorageImpl.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/storage/AppStorageTest.kt
=> [#1228] Storage refactoring

buildSrc/src/main/kotlin/Versions.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/ClientModule.kt, config/build.gradle.kts, config/src/androidMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/di/module/ConfigModule.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/di/module/submodule/RemoteServiceModule.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AdConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AppConfig.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AppReview.kt, config/src/commonMain/kotlin/com/oztechan/ccc/config/entity/AppUpdate.kt, config/src/iosMain/kotlin/com/oztechan/ccc/config/ConfigServiceImpl.kt
=> [#1252] creating DI module for config module

README.md
=> [#1260] Update_Architecture_Diagram

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/di/module/submodule/RepositoryModule.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/repository/api/ApiRepositoryImpl.kt, backend/src/jvmTest/kotlin/com/oztechan/ccc/backend/repository/ApiRepositoryTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/module/CommonModule.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/module/submodule/ScopeModule.kt
=> [#1271] Use global scope with DI

client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/submodule/StorageModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/submodule/ViewModelModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/ad/AdRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorage.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorageImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculator/CalculatorStorage.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculator/CalculatorStorageImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/adremove/AdRemoveViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AdRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/storage/AppStorageTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/storage/CalculatorStorageTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt
=> [#1278] Create CalculatorStorage

docs/CONTRIBUTING.md, docs/PULL_REQUEST_TEMPLATE.md
=> [Oztechan/CCC#1283] Update Docs for new Coding guidelines

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt
=> [Oztechan/CCC#1281] Show Loading only before API call

android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt
=> [Oztechan/CCC#1286] Fix navigation result bug for base change

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [Oztechan/CCC#1285] First rate download doesn't reflected on calculation

client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculator/CalculatorStorage.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/calculator/CalculatorStorageImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/storage/CalculatorStorageTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [Oztechan/CCC#1280] Remember last input

buildSrc/src/main/kotlin/Versions.kt
=> [Oztechan/CCC#1290] Dependency Updates

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [Oztechan/CCC#1295] Fix initial FewCurrency effect issue

ios/CCC/UI/Calculator/InputView.swift
=> [Oztechan/CCC#1293] Remove animation from input view

ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/SelectCurrency/SelectCurrencyView.swift, ios/CCC/UI/SubView/FormProgressView.swift
=> [Oztechan/CCC#1227] Fix iOS ProgressView Bug

buildSrc/src/main/kotlin/Versions.kt
=> [Oztechan/CCC#1298] Dependency Updates

client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/appconfig/AppConfigRepositoryImpl.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt
=> [Oztechan/CCC#1226] Fix RemoteConfig Logic

.github/workflows/release.yml, ios/fastlane/Fastfile
=> [Oztechan/CCC#1301] Fix Google Play Console upload issue

ios/fastlane/Fastfile
=> [Oztechan/CCC#1303] move upload_to_testflight to pilot

buildSrc/src/main/kotlin/ProjectSettings.kt
=> [Oztechan/CCC#1305] Adjust version code

ios/CCC/UI/Calculator/OutputView.swift, ios/CCC/UI/Currencies/CurrenciesToolbarView.swift, ios/CCC/UI/Currencies/SelectionView.swift, ios/CCC/UI/Settings/SettingsItemView.swift, ios/CCC/UI/Settings/SettingsToolbarView.swift, ios/CCC/UI/Slider/SlideView.swift, ios/CCC/UI/SubView/SelectCurrenciesBottomView.swift, ios/CCC/UI/Watchers/WatcherItem.swift, ios/CCC/UI/Watchers/WatchersToolbarView.swift, ios/CCC/Util/Extensions.swift
=> [Oztechan/CCC#1307] Create padding extension

ios/CCC/Util/ViewExt.swift
=> [Oztechan/CCC#1315] Add basic iPad Support

ios/CCC.xcodeproj/project.pbxproj, ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/Currencies/CurrenciesView.swift, ios/CCC/UI/Settings/SettingsView.swift, ios/CCC/UI/SubView/AdaptiveBannerAdView.swift, ios/CCC/UI/Watchers/WatchersView.swift
=> [Oztechan/CCC#1311] Move to AdaptiveBannerAd in iOS

.github/auto_move_related_issue.yml, .github/workflows/board.yml
=> [Oztechan/CCC#1325] Automate moving Related issue into PR Review

ios/CCC/UI/Settings/SettingsItemView.swift, ios/CCC/UI/Settings/SettingsToolbarView.swift, ios/CCC/UI/SubView/ToolbarButton.swift, ios/CCC/Util/ViewExt.swift
=> [Oztechan/CCC#1317] Add iPad friendly SettingsView

ios/Gemfile
=> [Oztechan/CCC#1339] Dependabot Gem file issue fix

buildSrc/src/main/kotlin/Versions.kt
=> [Oztechan/CCC#1337] Update Dependencies

.github/dependabot.yml
=> [Oztechan/CCC#1342] Update Dependabot PR title

.github/auto_move_related_issue.yml, .github/workflows/board.yml
=> [Oztechan/CCC#1344] Remove Issue automation

common/src/commonMain/kotlin/com/oztechan/ccc/common/di/module/submodule/ScopeModule.kt
=> [Oztechan/CCC#1346] Fix Backend DI issue

gradle/wrapper/gradle-wrapper.properties
=> [Oztechan/CCC#1359] Update Gradle

buildSrc/src/main/kotlin/Versions.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CoroutineUtil.kt, gradle/wrapper/gradle-wrapper.properties
=> [Oztechan/CCC#1358] Dependency Updates

backend/build.gradle.kts, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/VersionRoute.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/di/module/submodule/ScopeModule.kt
=> [Oztechan/CCC#1348] Add Version Route

backend/build.gradle.kts
=> [Oztechan/CCC#1363] Remove BuildKonfig from commonMain in backend module and make jvmOnly

build.gradle.kts, settings.gradle.kts
=> [Oztechan/CCC#1365] Reorganise project and settings gradle scripts

ios/CCC/UI/Calculator/CalculatorItemView.swift, ios/CCC/UI/Calculator/RateStateView.swift, ios/CCC/UI/Currencies/CurrenciesToolbarView.swift, ios/CCC/UI/SubView/FormProgressView.swift, ios/CCC/UI/SubView/SelectCurrenciesBottomView.swift, ios/CCC/UI/Watchers/WatcherItem.swift, ios/CCC/UI/Watchers/WatchersToolbarView.swift, ios/CCC/UI/Watchers/WatchersView.swift, ios/CCC/Util/Alert.swift, ios/CCC/Util/SnackBar.swift
=> [Oztechan/CCC#1335] Adjust missing iPad improvements

buildSrc/src/main/kotlin/Versions.kt
=> [Oztechan/CCC#1378] Kotlin Update

.github/dependabot.yml
=> [Oztechan/CCC#1384] Add Dependabot support for submodules

res/src/commonMain/resources/MR/base/strings.xml
=> [Oztechan/CCC#1352] String adjustments

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [Oztechan/CCC#1395] Remembering the output with spaces bug

ios/CCC/UI/Calculator/CalculatorView.swift
=> [Oztechan/CCC#1392] Fix Keyboard background shake issue

ios/CCC.xcodeproj/project.pbxproj, ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/CCC/UI/Main/MainView.swift
=> [Oztechan/CCC#1127] iOS Navigation slide direction bug

ios/CCC/UI/Calculator/OutputView.swift, ios/CCC/UI/SubView/ToolbarButton.swift
=> [Oztechan/CCC#1393] iPad Design Adjustment

.github/dependabot.yml
=> [Oztechan/CCC#1400] Update Dependabot PR title Prefix

.github/dependabot.yml, ad/build.gradle.kts, analytics/build.gradle.kts, android/build.gradle.kts, backend/build.gradle.kts, billing/build.gradle.kts, buildSrc/src/main/kotlin/Modules.kt, client/build.gradle.kts, common/build.gradle.kts, config/build.gradle.kts, res/build.gradle.kts, test/build.gradle.kts
=> [Oztechan/CCC#1403] Make Modules object

buildSrc/src/main/kotlin/Versions.kt
=> [Oztechan/CCC#1405] Dependency Updates

buildSrc/src/main/kotlin/Versions.kt
=> [Oztechan/CCC#1413] Update Kermit

ios/Gemfile.lock, ios/Podfile.lock, ios/fastlane/Fastfile
=> [Oztechan/CCC#1417] Make fastlane locally working

ios/CCC.xcodeproj/project.pbxproj, ios/CCC.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [Oztechan/CCC#1425] Update Swift Packages

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/client/ClientController.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/controller/client/ClientControllerImpl.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/di/module/submodule/ControllerModule.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/Client.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/repository/api/ApiRepository.kt
=> [Oztechan/CCC#1422] Extract ClientController

backend/build.gradle.kts, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/Application.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/ClientModule.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/LoggerModule.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/ServerModule.kt, backend/src/jvmMain/resources/application.conf, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Versions.kt
=> [Oztechan/CCC#1431] Create Logger Module for backend

backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/module/ServerModule.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/CurrencyRoute.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/ErrorRoute.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/RootRoute.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/VersionRoute.kt
=> [Oztechan/CCC#1406] Set missing content types and status for Ktor responds

.github/renovate.json
=> Oztechan/CCC#1443 Add renovate details and board automation into submodules

gradle/libs.versions.toml
=> [Oztechan/CCC#1501] Separate koin dependencies

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/slider/SliderFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt
=> [Oztechan/CCC#1507] Replace gone() visible() and invisible() with existing inline variables

android/src/main/kotlin/com/oztechan/ccc/android/ui/adremove/AdRemoveBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/calculator/CalculatorFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/currencies/CurrenciesFragment.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/selectcurrency/SelectCurrencyBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/ViewExtensions.kt
=> [Oztechan/CCC#1509] Merge visibleIf with showLoading

ad/build.gradle.kts, analytics/build.gradle.kts, android/build.gradle.kts, backend/build.gradle.kts, billing/build.gradle.kts, build.gradle.kts, client/build.gradle.kts, common/build.gradle.kts, config/build.gradle.kts, provider/build.gradle.kts, res/build.gradle.kts, test/build.gradle.kts
=> [Oztechan/CCC#1533] Add DSL_SCOPE_VIOLATION for libs error

ios/CCC/Util/Alert.swift
=> [Oztechan/CCC#1539] Make iOS Dialog button bigger

ad/build.gradle.kts, analytics/build.gradle.kts, android/build.gradle.kts, backend/build.gradle.kts, billing/build.gradle.kts, buildSrc/src/main/kotlin/Modules.kt, client/build.gradle.kts, common/build.gradle.kts, config/build.gradle.kts, provider/build.gradle.kts, res/build.gradle.kts, test/build.gradle.kts
=> [Oztechan/CCC#1536] Make Modules support gradle submodules

.github/renovate.json
=> [Oztechan/CCC#1553] Enable lock file maintenance

.github/workflows/main.yml, android/src/main/kotlin/com/oztechan/ccc/android/ui/slider/SliderFragment.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/ErrorRoute.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/routes/RootRoute.kt, build.gradle.kts, common/src/androidMain/kotlin/com/oztechan/ccc/common/di/module/submodule/AndroidDispatcherModule.kt, common/src/jvmMain/kotlin/com/oztechan/ccc/common/di/module/submodule/JVMDispatcherModule.kt, gradle/libs.versions.toml
=> [Oztechan/CCC#1398] Detekt integration

ad/src/google/kotlin/com/oztechan/ccc/ad/AdManagerImpl.kt, ad/src/huawei/kotlin/com/oztechan/ccc/ad/AdManagerImpl.kt, billing/src/google/kotlin/com/oztechan/ccc/billing/BillingManagerImpl.kt, build.gradle.kts, client/src/androidMain/kotlin/com/oztechan/ccc/client/util/AndroidCalculatorUtil.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AdRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt, gradle/libs.versions.toml
=> [Oztechan/CCC#1559] Add detekt formatting

ios/CCC/UI/Calculator/CalculatorView.swift, ios/CCC/UI/SubView/AlertView.swift
=> [Oztechan/CCC#1545] iPad design alignment

ios/CCC/Util/ObservableSEEDViewModel.swift
=> [Oztechan/CCC#1567] Improve ViewModel observation in iOS

ad/build.gradle.kts, analytics/build.gradle.kts, android/build.gradle.kts, backend/build.gradle.kts, billing/build.gradle.kts, build.gradle.kts, client/build.gradle.kts, common/build.gradle.kts, config/build.gradle.kts, provider/build.gradle.kts, res/build.gradle.kts, test/build.gradle.kts
=> [Oztechan/CCC#1574] Replace dependency blocks with apply

auto_move_related_issue.yml
=> [Oztechan/CCC#1535] Remove auto_move_related_issue.yml

client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/background/BackgroundRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/CalculatorUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/CalculatorUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt
=> [Oztechan/CCC#1579] Rename getConversionByCode and calculateResult

client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/calculator/CalculatorViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/currencies/CurrenciesViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/selectcurrency/SelectCurrencyViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/WatchersViewModelTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSourceImpl.kt, common/src/commonMain/sql/com/oztechan/ccc/common/database/sql/Currency.sq, common/src/commonMain/sql/com/oztechan/ccc/common/database/sql/Watcher.sq, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/CurrencyDataSourceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/datasource/WatcherDataSourceTest.kt
=> [Oztechan/CCC#1581] Unify Database Query methods and use conventional namings in DataSources

common/build.gradle.kts, common/src/commonMain/sql/com/oztechan/ccc/common/database/sql/migrations/5.sqm
=> [Oztechan/CCC#1584] Replace RENAME COLUMN to old school way

android/build.gradle.kts, android/src/main/AndroidManifest.xml, android/src/main/kotlin/com/oztechan/ccc/android/widget/AppWidget.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/AppWidgetReceiver.kt, android/src/main/res/xml/app_widget_info.xml, gradle/libs.versions.toml
=> [Oztechan/CCC#1589] Add Glance Widget

android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/theme/ApplicationTheme.kt, android/src/main/res/drawable/ic_cached.xml, android/src/main/res/drawable/ic_offine.xml, android/src/main/res/drawable/ic_online.xml, android/src/main/res/values/colors.xml, android/src/main/res/values/styles.xml, ios/CCC/UI/Components/ActionButton.swift, ios/CCC/UI/Currencies/CurrenciesItemView.swift, ios/CCC/Util/ConversionStateExt.swift, res/src/commonMain/resources/MR/colors/colors.xml
=> [Oztechan/CCC#1592] Reorganise colors for Compose

android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/content/watchers/WatchersView.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/watchers/WatchersSEED.kt
=> [Oztechan/CCC#1522] Replace interface mocking with lambdas for Previews

android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/WidgetItem.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/WidgetView.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/submodule/ViewModelModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
=> [Oztechan/CCC#1604] Print active currencies in Widget

build.gradle.kts, detekt.yml
=> [Oztechan/CCC#1590] Add custom detekt configuration

build.gradle.kts
=> [Oztechan/CCC#1622] Exclude Composable and its Previews from coverage reports

android/src/main/kotlin/com/oztechan/ccc/android/util/Dialog.kt, android/src/main/kotlin/com/oztechan/ccc/android/util/SnackBar.kt, backend/src/jvmMain/kotlin/com/oztechan/ccc/backend/di/module/submodule/ControllerModule.kt, detekt.yml
=> [Oztechan/CCC#1614] Activate detekt NamedArguments rule

.github/renovate.json
=> [Oztechan/CCC#1586] Remove schedule for lockFileMaintenance

android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/component/ImageView.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/component/Preview.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/content/watchers/WatcherItem.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/content/watchers/WatchersView.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/theme/AppTheme.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/FooterView.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/HeaderView.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/WidgetItem.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/WidgetView.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/components/ImageView.kt, detekt.yml
=> [Oztechan/CCC#1626] Disable FunctionNaming rule for composable functions

client/build.gradle.kts
=> [Oztechan/CCC#1632] Remove sqlDelight plugin from client

.github/workflows/main.yml, build.gradle.kts, gradle/libs.versions.toml
=> [Oztechan/CCC#1628] Sonar integration

android/src/main/AndroidManifest.xml, client/src/androidMain/kotlin/com/oztechan/ccc/client/di/module/submodule/AndroidViewModelModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/submodule/ViewModelModule.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/iosMain/kotlin/com/oztechan/ccc/client/di/module/submodule/IOSViewModelModule.kt, ios/CCC/UI/Components/AdaptiveBannerAdView.swift, ios/CCC/UI/Components/MailView.swift
=> [Oztechan/CCC#1640] Fix some Sonar issues

README.md
=> [Oztechan/CCC#1642] [unordered-list-marker-style] Marker style should be `-`

client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AdRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AppConfigRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/storage/AppStorageTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/storage/CalculatorStorageTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/AdRemoveViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CalculatorViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/CurrenciesViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SelectCurrencyViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/BackendApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/FreeApiServiceTest.kt, common/src/commonTest/kotlin/com/oztechan/ccc/common/service/PremiumApiServiceTest.kt
=> [Oztechan/CCC#1643] Function names should match the pattern: ([a-z][a-zA-Z0-9]*)|(`.*`)

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/testing.yml
=> [Oztechan/CCC#1654] Move Gradle commands into gradle build action

codecov.yml
=> [Oztechan/CCC#1667] Update Codecov config for PR comment

.github/workflows/testing.yml, ios/fastlane/Fastfile
=> [Oztechan/CCC#1672] Move Distributing into new workflow

android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/ad/AdRepository.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/ad/AdRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AdRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, codecov.yml, ios/CCC/UI/Settings/SettingsView.swift
=> [Oztechan/CCC#1663] Remove showing Remove Ads condition

.github/workflows/main.yml
=> [Oztechan/CCC#1652] Disable Shallow clone for Quality job

analytics/src/commonMain/kotlin/com/oztechan/ccc/analytics/model/UserProperty.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/premium/PremiumAdapter.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/premium/PremiumBottomSheet.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/settings/SettingsFragment.kt, android/src/main/res/layout/item_premium.xml, android/src/test/kotlin/com/oztechan/ccc/android/util/PurchaseUtilTest.kt, billing/src/google/kotlin/com/oztechan/ccc/billing/BillingManagerImpl.kt, billing/src/main/kotlin/com/oztechan/ccc/billing/BillingEffect.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/PremiumData.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/model/PremiumType.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/repository/ad/AdRepositoryImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorage.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/storage/app/AppStorageImpl.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/util/DateUtil.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/main/MainViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/premium/PremiumViewModel.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsSEED.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/settings/SettingsViewModel.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/repository/AdRepositoryTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/storage/AppStorageTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/util/DateUtilTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/MainViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/PremiumViewModelTest.kt, client/src/commonTest/kotlin/com/oztechan/ccc/client/viewmodel/SettingsViewModelTest.kt, ios/CCC/UI/Settings/SettingsView.swift
=> [Oztechan/CCC#1675] Replace AddFree and Reward Logic with Premium

android/src/main/kotlin/com/oztechan/ccc/android/widget/AppWidget.kt, android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/WidgetView.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetState.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
=> [Oztechan/CCC#1681] Add WidgetState for holding state

.gitignore, .gitmodules, settings.gradle.kts
=> [Oztechan/CCC#1679] Move submodules into submodule folder

client/src/commonTest/kotlin/com/oztechan/ccc/client/storage/CalculatorStorageTest.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/BaseDBDataSource.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/currency/CurrencyDataSourceImpl.kt, common/src/commonMain/kotlin/com/oztechan/ccc/common/datasource/watcher/WatcherDataSourceImpl.kt
=> [Oztechan/CCC#1650] Use stateIn in DataSources

android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/component/SnackViewHost.kt, android/src/main/kotlin/com/oztechan/ccc/android/ui/compose/content/watchers/WatchersView.kt
=> [Oztechan/CCC#1620] Add Snackbar

gradle/libs.versions.toml
=> [Oztechan/CCC#1691] Revert androidGradlePlugin version

android/src/main/kotlin/com/oztechan/ccc/android/widget/ui/WidgetView.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/di/module/submodule/ViewModelModule.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetState.kt, client/src/commonMain/kotlin/com/oztechan/ccc/client/viewmodel/widget/WidgetViewModel.kt
=> [Oztechan/CCC#1666] Implement Premium logic for Widget

.github/workflows/project.yml
=> [Oztechan/CCC#1699] Add custom_field_values through secrets for multiple tries
